### ISSUE TITLE
Office files don't get deleted

### ISSUE THREAD

**Issue by Cyb3r-Monk** [cmu-sei/GHOSTS#112]
I have the below Excel timeline and max age for the files is 72 hours:
```JSON
    {
      "HandlerType": "Excel",
      "Initial": "",
      "UtcTimeOn": "08:00:00",
      "UtcTimeOff": "17:30:00",
      "HandlerArgs": {},
      "Loop": true,
      "TimeLineEvents": [
        {
          "TrackableId": null,
          "Command": "create",
          "CommandArgs": [
            "%homedrive%%homepath%\\Documents",
            "pdf",
            "pdf-vary-filenames",
            "save-array:['c:\\tmp','c:\\tmp\\path2','c:\\tmp\\path3']"
          ],
          "DelayAfter": 7200000,
          "DelayBefore": 0
        }
      ]
    }
```
For the files that are saved to Documents folder, I'm seeing the below message in the logs and the files don't get deleted.
`Ghosts.Client.Infrastructure.FileListing.FlushList|Delete evaluation for C:\ghosts\Association.pdf 1/1/1601 12:00:00 AM vs. 8/14/2022 7:25:04 AM`

The file "application_top.xslx" was created on `‎8/14/‎2022 ‏‎8:21:48 AM` but I'm seeing the below message and the file doesn't get deleted(look at the error timestamp and the timestamps that are compared). 
`2022/08/17 06:09:01.762|Ghosts.Client.Infrastructure.FileListing.FlushList|Delete evaluation for c:\tmp\application_top.xlsx 8/14/2022 8:21:48 AM vs. 8/14/2022 6:09:01 AM`

Seems like the file scanning module is not working properly.

**Comment by sei-dupdyke** [comment]
Hmm, the file deletion feature works for me.

> For the files that are saved to Documents folder, I'm seeing the below message in the logs and the files don't get deleted.
Ghosts.Client.Infrastructure.FileListing.FlushList|Delete evaluation for C:\ghosts\Association.pdf 1/1/1601 12:00:00 AM vs. 8/14/2022 7:25:04 AM

17th century files are definitely supported, and this file should delete. What comes after this log entry? You should see the following entries:

`Deleting: {fileName}`

If this fails for some reason, then you would see:

`Could not delete file {fileName}: {error}`

If neither of these entries appears, then the file did not pass the delete check, but I can't get that scenario to play out here, sorry.

> The file "application_top.xslx" was created on ‎8/14/‎2022 ‏‎8:21:48 AM but I'm seeing the below message and the file doesn't get deleted(look at the error timestamp and the timestamps that are compared).
2022/08/17 06:09:01.762|Ghosts.Client.Infrastructure.FileListing.FlushList|Delete evaluation for c:\tmp\application_top.xlsx 8/14/2022 8:21:48 AM vs. 8/14/2022 6:09:01 AM

If you've got the config set to the default 72 hours, this file is not old enough to delete yet (~2 hours). Did you expect this file to delete? Sorry if I am not understanding this case correctly.

**Comment by Cyb3r-Monk** [comment]
Oh sorry, I made a wrong calculation.  I changed the MaxAgeHour to 12, restarted the agent and the files were deleted except the ones in the Documents folder. I didn't see any errors or `Deleting: {filename}` in the logs(it got flushed at some point).

The other problem is GHOSTS agent checking the wrong directories. There is no Office file saved under ghosts directory. It also checks Windows directory as well. I haven't configured anything to save files under these folders. Since the file doesn't exist, it somehow uses the `1/1/1601 12:00:00 AM` timestamp. System32 folder and Program Files directory logs: 
```
2022/08/17 14:12:21.209|Ghosts.Client.Infrastructure.FileListing.FlushList|Delete evaluation for C:\Windows\system32\CREDITS.pdf 1/1/1601 12:00:00 AM vs. 8/14/2022 2:12:21 PM 

2022/08/17 14:27:54.975|Ghosts.Client.Infrastructure.FileListing.FlushList|Delete evaluation for C:\Program Files\Microsoft Office\Root\Office16\stats.pdf 1/1/1601 12:00:00 AM vs. 8/17/2022 2:27:54 AM
```
These 2 files are in the Documents folder. So, the issue is about the files created in Documents folder ("%homedrive%%homepath%\\Documents") as far as I can see.

**Comment by sei-dupdyke** [comment]
This is fixed. I patched the current version. Sorry for the inconvenience.

**Comment by Cyb3r-Monk** [comment]
How can I get the current patched version? My ghosts version is 6.1.0.0(downloaded from cmu.box.com)

**Comment by sei-dupdyke** [comment]
It's the same download, the patch version just has a different file version:

![image](https://user-images.githubusercontent.com/43444464/185221333-c4c94b20-6034-46f3-a7d5-723203d97a52.png)

**Comment by Cyb3r-Monk** [comment]
Thanks for the amazing speed, Dustin!

**Comment by Cyb3r-Monk** [comment]
@sei-dupdyke now I'm getting the below error. Excel exits and no files are written to Documents folder. I see files written under C:\tmp folder, though. 
`Ghosts.Client.Infrastructure.FileListing.Add|System.IO.IOException: The process cannot access the file 'C:\exercise\ghosts\instance\files-created.log' because it is being used by another process.`

**Comment by sei-dupdyke** [comment]
This is fixed in the latest patch.

**Comment by Cyb3r-Monk** [comment]
I'm not seeing any files saved under the Documents folder (the same config above). Is this normal with the patched version?

**Comment by sei-dupdyke** [comment]
Do you have values in "save-array"?

"save-array:['c:\\tmp','c:\\tmp\\path2','c:\\tmp\\path3']"

If so, then it will save there, not in documents.

**Comment by Cyb3r-Monk** [comment]
Yes, I have it. So, everything is working as expected then. Thanks a lot, Dustin!
