### ISSUE TITLE
Feature Request: Schedule based on day of the week or month

### ISSUE THREAD

**Issue by Cyb3r-Monk** [cmu-sei/GHOSTS#117]
It would be nice have a scheduling mechanism like:
- Every Friday
- Every 20th day of the month/week

Since the machine or the ghosts.exe can be restarted, it's not feasible to set a delay as several days.

**Comment by sei-dupdyke** [comment]
I've been looking at quartz.net as a scheduler. It allows for all types of schedules, but cron-style markup would likely work well for this. 

I have a test project running, but this change is relatively large and will take some time to resolve. It may be the impetus to start planning the version 7.x launch party, as it will likely change timeline configuration significantly.  🥳

**Comment by Cyb3r-Monk** [comment]
Can we also use jitter functionality with cron like scheduling? For example: Create a word doc every 2 days at 13:30, but do it between 13:30-13:40, set a random sleep between 0-10minutes.

**Comment by sei-dupdyke** [comment]
Cron scheduling sits a layer above where jitter occurs, so whether we set up a job using traditional scheduling or new cron schedules, jitter remains the same - so if you were going to jitter before, and wanted that to persist with some new cron schedule - you're good to go.

**Comment by Cyb3r-Monk** [comment]
Awesome! Looking forward to the release 🥳

**Comment by Cyb3r-Monk** [comment]
Is this included in the 7.0.35.0 or still in progress?

**Comment by sei-dupdyke** [comment]
This should be fully functioning. Closing this. Any issues would be a new issue I think.

**Comment by Cyb3r-Monk** [comment]
Awesome! Thanks a lot!
