### ISSUE TITLE
Feature Request: Open links, attachments inside an email

### ISSUE THREAD

**Issue by Cyb3r-Monk** [cmu-sei/GHOSTS#124]
Opening links and attachments that are inside a received email would be great. Additionally a whitelist/blacklist for the links/attachments like domains, file extension names, etc. woule be great!

**Comment by sei-dupdyke** [comment]
[6.2.0](https://github.com/cmu-sei/GHOSTS/releases/tag/v6.2.0) introduces "click on a random link in an inbox email".

[The timeline format](https://github.com/cmu-sei/GHOSTS/blob/master/src/Ghosts.Client/Sample%20Timelines/Outlook.json) is simply:

`"Command": "clickrandomlink",`

With no additional configuration. A random email is selected from the inbox and a random link within that email is clicked.

Unless of course its (sub)domain is in the deny list located in ./config/denylist.txt

The format here is simply:

```txt
herein_lies_the_format_of_the_deny_list.org
we_can_deny_entire_domains.com
or_some_subnet.of_some_domain.net
```

Will look at attachments soon.

**Comment by Cyb3r-Monk** [comment]
Can the logic be like below?
First, check if there is an unread email and click link(s) if there are any(this may collide with email reply functionality when there is an unread email containing a link)
If no unread emails, randomly select an email and click a link if there is any. 

Maybe an unread email handler section would be better for email with attachments/links/text content.

**Comment by sei-dupdyke** [comment]
This looks to be good as of 6.2, and revised through the last 7.x updates. Closing. If there are some use-case that is outside what we currently have, we can revisit at that time.

**Comment by Cyb3r-Monk** [comment]
Does opening attachments work now, too, or just the link opening?

**Comment by sei-dupdyke** [comment]
Just links at this point I believe.
