### ISSUE TITLE
Logs are filled with actions but no data in database / grafan

### ISSUE THREAD

**Issue by brandon-bailey** [cmu-sei/GHOSTS#125]
![image](https://user-images.githubusercontent.com/10648463/189240970-58fd90ca-88f3-48a9-9c77-2331fcd9b66a.png)

I have connected directly to the postgresql database and run the SQL from the grafana dashboards just to make sure that was not the problem. But there is no data being sent to the database from the windows client other than the polling.

**Comment by brandon-bailey** [comment]
It appears to be related to this:
```
Ghosts.Client.Comms.Updates.PostClientResults|C:\ghosts\logs\clientupdates.log is locked, sleeping for 15000...
```
This is found everytime PostClientResults is called. Not sure why the file is staying locked

**Comment by sei-dupdyke** [comment]
Looking at this now. What version are you running please? (`ghosts.exe --version`) or the file version in the right-click properties window: 
![image](https://user-images.githubusercontent.com/43444464/189385073-4dd01fdd-405b-4459-8fc8-016384f70801.png)
Thank you.

**Comment by brandon-bailey** [comment]
I am running 6.1.0.0

**Comment by brandon-bailey** [comment]
6.2.0.0 seems to be showing the same thing
```
2022/09/09 22:28:02.480|Ghosts.Client.Comms.Updates.PostClientResults|C:\ghosts\logs\clientupdates.log is locked, sleeping for 15000...
2022/09/09 22:28:17.486|Ghosts.Client.Comms.Updates.PostClientResults|C:\ghosts\logs\clientupdates.log is locked, sleeping for 15000...
2022/09/09 22:28:32.499|Ghosts.Client.Comms.Updates.PostClientResults|C:\ghosts\logs\clientupdates.log is locked, sleeping for 15000...
2022/09/09 22:28:47.515|Ghosts.Client.Comms.Updates.PostClientResults|C:\ghosts\logs\clientupdates.log is locked, sleeping for 15000...
2022/09/09 22:29:02.529|Ghosts.Client.Comms.Updates.PostClientResults|C:\ghosts\logs\clientupdates.log is locked, sleeping for 15000...
2022/09/09 22:29:17.534|Ghosts.Client.Comms.Updates.PostClientResults|C:\ghosts\logs\clientupdates.log is locked, sleeping for 15000...
2022/09/09 22:29:32.541|Ghosts.Client.Comms.Updates.PostClientResults|C:\ghosts\logs\clientupdates.log is locked, sleeping for 15000...
2022/09/09 22:29:47.551|Ghosts.Client.Comms.Updates.PostClientResults|C:\ghosts\logs\clientupdates.log is locked, sleeping for 15000...
2022/09/09 22:30:02.557|Ghosts.Client.Comms.Updates.PostClientResults|C:\ghosts\logs\clientupdates.log is locked, sleeping for 15000...
2022/09/09 22:30:17.569|Ghosts.Client.Comms.Updates.PostClientResults|C:\ghosts\logs\clientupdates.log is locked, sleeping for 15000...
2022/09/09 22:30:32.578|Ghosts.Client.Comms.Updates.PostClientResults|C:\ghosts\logs\clientupdates.log is locked, sleeping for 15000...
```

![image](https://user-images.githubusercontent.com/10648463/189454444-5e8f260c-2916-4edd-901e-71a0e326b3d9.png)

**Comment by sei-dupdyke** [comment]
Sorry about this, I finally found the issue this evening and posted a fix with the 6.2.1 version of the linux client. For some reason the logging framework seems to lock the file for reading by other processes that post that data up to the API. I think the current fix is probably a better method, and I'll copy that same process to the Windows client as well when i get a chance.

The fix was to make a temp copy of the log, zero the log, read the copy, and then delete the temp file after success postback. If for some reason the API postback fails, I put the logs back into the original file.

Again, I apologize for the error. Thank you for reporting this and your patience.

**Comment by sei-dupdyke** [comment]
Oops, leaving this open to make sure this makes its way to Windows as well.

**Comment by brandon-bailey** [comment]
Awesome, thank you. Looking forward to testing it on windows!

**Comment by sei-dupdyke** [comment]
This has been fixed in both the Linux and Windows clients (6.2.2). Please LMK if you see anything amiss.

**Comment by brandon-bailey** [comment]
Bingo!
![image](https://user-images.githubusercontent.com/10648463/190690539-1ef18134-dde9-4778-8138-f19870ffffa9.png)

**Comment by sei-dupdyke** [comment]
Looks great, thank you for your patience.
