### ISSUE TITLE
Cannot start up ghosts pandora

### ISSUE THREAD

**Issue by melmelchew** [cmu-sei/GHOSTS#133]
Hi Dustin! I wanted to set up the pandora server to use it alongside the ghosts client in making get requests, however I am not able to docker-compose as it is saying the requested access to the resource is denied. May I know when will the pandora server be available for use? 

Also, do you think it is possible for the ghosts client to make use of the received contents from the pandora server in generating content for emails or word docs?

Thanks a bunch! :D

**Comment by sei-dupdyke** [comment]
Hi, sorry I had not pushed a built container to docker-hub, but it is there now: https://hub.docker.com/r/dustinupdyke/ghosts-pandora v0.4.1 - the latest now supports serving video as well (but I am still testing it).

Are you looking for a specific use case regarding using the content for emails and docs?

**Comment by melmelchew** [comment]
Thank you! Am able to pull the docker image 👍 

Correct me if I am mistaken, from my current experiments with ghosts client and looking through the code, the email and docs content are generated randomly using data in specified files, which would make the emails sent and docs created seem rather odd at times. I was hoping that maybe I could make use of the content retrieved from the pandora server (or maybe even other self hosted servers like python's in-built http servers) and use it to directly fill up the email or docs, rather than random content generation or selection from a pre-written local file.
Thought it would be interesting to make use of the contents retrieved from pandora in such a way (more so for emails) on top of downloading it into the client computer to generate user activity 😄

**Comment by sei-dupdyke** [comment]
Hmm, as it is, I had through that people update those files in the config directory with some host/file based tool, like Ansible or similar.

But this as you explain this - it is an interesting use case, let me think about how best to implement it 🤔
