### ISSUE TITLE
Exclude login and privacy URLs when crawling web pages

### ISSUE THREAD

**Issue by Cyb3r-Monk** [cmu-sei/GHOSTS#147]
When there is a login button or link to the privacy on a website and browser crawls the URL, it kinda gets stuck because there is no URL left to crawl. Is it possible to exclude these links or make it configurable? How can the agent avoid those crawling these links?

**Comment by sei-dupdyke** [comment]
Do you have an example url please?

**Comment by Cyb3r-Monk** [comment]
`netbasequid.com`. When you click the login button, there are only few links to crawl and the agent starts visiting google support pages etc.

**Comment by sei-dupdyke** [comment]
I'm adding the deny list as having three possible variations:

- some_domain.com/cb/nb/some_page_to_specifically_deny.html

In this case, any URL that starts with this string gets denied.

- */some_url_to_specifically_deny_across_all_domains

Here, the if the URL ends with this string, it gets denied.

- *some_word_to_deny_across_space_and_time*

Any URL containing this string gets denied.

**Comment by Cyb3r-Monk** [comment]
Awesome, thanks!

**Comment by sei-dupdyke** [comment]
This is complete, will be available in the next build.
