### ISSUE TITLE
Feature Request: DevOps / Cloud activity simulation

### ISSUE THREAD

**Issue by Cyb3r-Monk** [cmu-sei/GHOSTS#150]
I don't know if it make sense but I feel like it would be nice to simulate regular activities happening in the cloud, mostly DevOps/Sysadmin related tasks. Some examples: creating/deleting services, starting/stopping/deleting VMs, upload/download/delete files from S3/blob storages, etc.

**Comment by Cyb3r-Monk** [comment]
Some new ideas related to this: 
On a machine that has Git installed adn configured, create/clone/have a repo (maybe manually), then let the agent add some simple text/comment to the README or some .py files, then do git add/commit/push.

**Comment by sei-dupdyke** [comment]
I like this, we could have agents start a dev war with git blame too 😁 

Automating git seems trivial, but what about the server portion? I'm not sure I want to build support around that, it might be a decent amount of work.

**Comment by Cyb3r-Monk** [comment]
No need for server portion I think. We can manually install git and configure the server authentication etc. Just need to automate the file creation/modification + git commands. If we assign one file to each agent, then fetching the latest changes before and after commit+push/merge, we wouldn't have any conflict issues I guess. Th enext step would be the agents developing the GHOSTS 😅

**Comment by sei-dupdyke** [comment]
Closing as not prioritized. Reopenable.
