### ISSUE TITLE
Internal server error in API

### ISSUE THREAD

**Issue by CyberDen1** [cmu-sei/GHOSTS#159]
After installing ghosts in UBUNTU and navigating to 172.16.1.127:52388/api/clientid there is an error 500. Can you please tell me what the problem is?

The curl command on the API page also causes a 500 error

Ghosts was installed via docker-compose

**Comment by sei-dupdyke** [comment]
Please see this issue, I can't recreate it here and have no idea why this is happening. Still researching. https://github.com/cmu-sei/GHOSTS/issues/154

**Comment by CyberDen1** [comment]
Yes, I watched that question. Unfortunately, nothing helped.

**Comment by sei-dupdyke** [comment]
I'm closing this issue because it is the same as the previous one. Easier to track.
