### ISSUE TITLE
Use tabs for multiple Chrome handlers

### ISSUE THREAD

**Issue by Cyb3r-Monk** [cmu-sei/GHOSTS#160]
When using multiple handlers for Chrome, separate browsers are opened. Is it possible to use one browser with tabs?

**Comment by sei-dupdyke** [comment]
Possibly, but why? From a resourcing perspective, a tab or a window is the same — a separate sandboxed process, right?

**Comment by Cyb3r-Monk** [comment]
I don't know if they are the same tbh. If it's so, there is no need.

**Comment by sei-dupdyke** [comment]
Since this is maybe a "nice-to-have", but not a must, I'm closing this for the time being. Sorry.
