### ISSUE TITLE
Word-Excel-PowerPoint Handlers don't accept relative paths in save-array

### ISSUE THREAD

**Issue by Cyb3r-Monk** [cmu-sei/GHOSTS#166]
Word-Excel-PowerPoint Handlers seem like they don't accept relative paths in save-array argument. Sample config:
```JSON
      "TimeLineEvents": [
        {
          "TrackableId": null,
          "Command": "create",
          "CommandArgs": [
            "%homedrive%%homepath%\\Documents",
            "pdf",
            "pdf-vary-filenames",
            "save-array:['%homedrive%%homepath%\\Myfolder\\Sales','%homedrive%%homepath%\\Myfolder\\Personal']"
          ],
          "DelayAfter": 1800000,
          "DelayBefore": 300000
        }
      ]
```

**Comment by sei-dupdyke** [comment]
Added with #39d5e12fe9a3f9c2d1e274b5624571ff947a9cc0

**Comment by sei-dupdyke** [comment]
Note to self:

 if you need to resolve paths of all types, such as:
 
c:\temp
some\relative\path
\\server\share\file
 
Path.GetFullPath(Path.Combine(current_app_directory, path_to_resolve));
 
handles all of these quite nicely...
