### ISSUE TITLE
Feature Request: Perform login to the supported web sites

### ISSUE THREAD

**Issue by Cyb3r-Monk** [cmu-sei/GHOSTS#168]
It would be nice to simulate user login for some web sites that is supported by GHOSTS. Some web sites to support: Facebook, Instagram, Twitter, Outlook.com, OWA(Outlook Web Access), AWS Console, Azure Portal, etc. It could be based on some requirements like having a certain HTML tag. This would also generate realistic HTTP POST events.

**Comment by sei-dupdyke** [comment]
Thinking about this, i think it would be best to have a general form handler that is easy to use?

**Comment by Cyb3r-Monk** [comment]
Could be. On the other hand, many Web sites keep you signed in when you once signed in manually. I manually signed in to the sites and let the agent do the rest for now.

**Comment by sei-dupdyke** [comment]
Not sure we still need this. Can reopen if it pops back up.
