### ISSUE TITLE
Client chrome "type" option issue

### ISSUE THREAD

**Issue by danielgarner64** [cmu-sei/GHOSTS#17]
I tried to use the "type" option and provide text in the timeline.json file for the ghost client on a windows 10 machine.
I had problems making it work and found that the current version of selenium is incompatible with newer versions of chrome (76) was the one I used.
It was causing an error in this section of code in the BaseBrowser.cs file.
```
case "type":
    IWebElement e = Driver.FindElement(By.Name(timelineEvent.CommandArgs[0].ToString()));
    e.SendKeys(timelineEvent.CommandArgs[1].ToString());
     //this.Report(timelineEvent);
    break;
```
Basically the SendKeys function wouldn't work because selenium didn't support the function.

An alternative approach to fix the problem which I also used was to modify the "type" function to work as follows (I couldn't test the code but it was something like this):
```
case "type":
    IWebElement element = Driver.FindElement(By.Name(timelineEvent.CommandArgs[0].ToString()));
    Actions actions = new Actions(Driver);
    actions.SendKeys(element, timelineEvent.CommandArgs[1].ToString()).Build().Perform();
    break;
```

**Comment by sei-dupdyke** [comment]
Thanks for reporting, I will take a look and merge this into master as soon as I can.
