### ISSUE TITLE
Client installation packages are not up-to-date

### ISSUE THREAD

**Issue by Cyb3r-Monk** [cmu-sei/GHOSTS#174]
There have been changes since Nov 2022, but the client package files don't seem to be updated. 

<img width="918" alt="image" src="https://user-images.githubusercontent.com/26627224/216758282-783cf041-612e-407a-a3df-65b2d25ede61.png">

**Comment by sei-dupdyke** [comment]
Hi

There are two reasons for this, (1) we don't always produce a build with code updates to master, and (2) we've been working on v7 on the development branch and I think that will be the next release and that we will do that soon, but I don't have a specific timetable for that.

Is there something you are looking for that was added that is not in the current build?

**Comment by Cyb3r-Monk** [comment]
Oh, got it! I was curious to try new handlers but I can wait for the v7 :)
Just wondering, are you going to add the new scheduling feature suggested in #117?

**Comment by sei-dupdyke** [comment]
I have a working prototype of that, and I think we can get that into v7, yes 🤞

**Comment by sei-dupdyke** [comment]
[v7 is official](https://github.com/cmu-sei/GHOSTS/releases/tag/v7.0.0). It does not currently include cron-style scheduling, but that is coming. 

I am going to close this issue, because the scheduling request already exists in #117, as you stated. Thanks.

**Comment by Cyb3r-Monk** [comment]
Awesome!
