### ISSUE TITLE
Enhancement: Browsing by name only

### ISSUE THREAD

**Issue by danielgarner64** [cmu-sei/GHOSTS#18]
Currently the browser can only find elements by 'name'.
I suggest having options in the timeline for:
typeById
typeByName
ClickById
ClickByName

This way you can select html elements by Ids if the page doesn't have names on specific elements. (You could maintain backwards compatibility by simply adding an option ClickById and leaving Click as the by name default)
Being able to select an element based on a parent and then child of that parent would be nice but harder to implement.

**Comment by sei-dupdyke** [comment]
I left type and click as is, and added typebyid and clickbyid.
