### ISSUE TITLE
Single docker-compose deploy with a thorough walkthrough in docs

### ISSUE THREAD

**Issue by mamik202** [cmu-sei/GHOSTS#181]
Can we please get a more thorough setup guide.  I am constantly running into issues and can't get things working as intended.  Usually you can find a guide somewhere but no one has seemed to make one.

**Comment by sei-dupdyke** [comment]
Did you have a look at the docs, specifically the quick start here? https://cmu-sei.github.io/GHOSTS/quickstart/

What issues are you seeing? What parts of ghosts are you trying to use?

**Comment by sei-dupdyke** [comment]
Something beneficial would be to have single docker-compose file repo where the entire stack is setup and configured with one "compose up" command.
