### ISSUE TITLE
Enhancement: Timeline configuration instructions

### ISSUE THREAD

**Issue by danielgarner64** [cmu-sei/GHOSTS#19]
https://github.com/cmu-sei/GHOSTS/wiki/Configuration-Timeline-Handlers
The timeline configuration is incomplete for chrome.
browse should say browses to the first CommandArg provided (CommandArgs[0]).
Type should say it finds element by name at (CommandArgs[0]) and then types the text of CommandArgs[1] into that field (throws an error if two args aren't provided).

**Comment by sei-dupdyke** [comment]
Thanks for reporting - updated the wiki and added an example in the sample timeline section.
