### ISSUE TITLE
Where is documentation for TimelineEvent?

### ISSUE THREAD

**Issue by LeukocytesTT** [cmu-sei/GHOSTS#191]
How can I get documentation for TimelineEvent which is about some params such as DelayAfter, DelayBefore? Who can show me the meaning of them, please?

**Comment by sei-dupdyke** [comment]
Hi -

Consider we want an agent to browse some website with Firefox in a loop, 1 site every 15 minutes, here is what happens under the covers:

1. Firefox opens and waits for the `delaybefore` value
2. Firefox browses the appropriate site
3. Firefox waits for the `delayafter` value
4. We return to step (1)

Either (or both) delay values could be zero.
