### ISSUE TITLE
Can't flush the files when the timestamp format has AM/PM 

### ISSUE THREAD

**Issue by Cyb3r-Monk** [cmu-sei/GHOSTS#196]
I started getting the below error:
```
Ghosts.Client.Infrastructure.FileListing.FlushList|Error flushing C:\exercise\ghosts\instance\files-created.log: System.FormatException: String was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at System.Convert.ToDateTime(String value)
   at Ghosts.Client.Infrastructure.FileListing.FlushList() in C:\Projects\ghosts\src\Ghosts.Client\Infrastructure\FileListing.cs:line 105
````
I think it started after changing the locale settings. Now I'm seeing the entries in the `files-created.log` like below which is causing the error:
```
3/25/2023 3:41:42 PM|Excel|C:\Users\testuser\Personal\index.class.pdf
```
The old entires doesn't have AM/PM format.

**Comment by sei-dupdyke** [comment]
Sorry, what locale settings were changed? This file should be simply:

create_date|file_name

and is wholly managed by the ghosts client - nothing else should be modifying this file.

**Comment by Cyb3r-Monk** [comment]
The files-created.log had two different time formats because of locale change.
```
21/03/2023 15:22:02|Excel|C:\temp\path1\sessionRead.xlsx
4/3/2023 3:03:18 PM|Word|c:\tmp\path2\hello_dolly.pdf
``` 

Maybe having 2 different timestamp formats caused the issue.

**Comment by sei-dupdyke** [comment]
Ah, I would just delete that file when you change locales. The problem is now there are two formats for 1 locale.
