### ISSUE TITLE
Installation Server API issue

### ISSUE THREAD

**Issue by e101sg** [cmu-sei/GHOSTS#201]
Dear community,  Trying to install the  GHOSTS API Server on Ubuntu 22.04 laptop. Following the Quick start guide and nice guide here.. [https://cylab.be/blog/71/simulate-user-activity-with-the-ghosts-framework-introduction]. Seems the docker installation has done without however when run the   **http://localhost:5000/api/home** getting error as seen in the following screen shot 1.
also the ghosts Postgres DB at: **http://localhost:5432/**  does not anything.

On the screen shot 2 shown the PostgreSQL database. Seems all right?  Am i missing anything?  
Any suggestions /thoughts highly useful. Cheers!

### Screen shot 1: 
![docker_5000](https://user-images.githubusercontent.com/1925934/228225629-d7667b6f-8ea4-450e-af33-3fa62125c017.png)

### Screen shot 2: 
![docker_database](https://user-images.githubusercontent.com/1925934/228226355-816f0c47-bed3-4be6-a90e-d46e560ee937.png)

**Comment by e101sg** [comment]
Hi,  
Following the hints and restart my laptop, restart the Docker and run  `docker-compose up -d`
I am getting the output as shown in the screen shot.  Seems it working.  Able to see the login into Grafana and create a dashboard using import method. 

**Screen shot:**

![local_host_5000](https://user-images.githubusercontent.com/1925934/228437091-989fceab-bcaf-413e-ab67-22a1892145b5.png)

172.18 address may come from  docker container IP, right ?
`docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ghosts-postgres`

**Comment by sei-dupdyke** [comment]
Looks good, glad you got it working!
