### ISSUE TITLE
RDP Handler not working on 64bit Server OS

### ISSUE THREAD

**Issue by joe-thompson-exa** [cmu-sei/GHOSTS#208]
Hi,

Attempting to use the RDP handler in a timeline and getting the following error:
`2023/04/13 15:29:04.778|Ghosts.Client.Handlers.Rdp..ctor|System.Runtime.InteropServices.COMException: Retrieving the COM class factory for component with CLSID {1A671297-FA74-4422-80FA-6C5D8CE4DE04} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).`

The OS it's running on is:
Windows Server 2016 Datacenter
64-Bit Operating System

I have tried both the 64 and 32 bit builds of GHOSTS and same error in each.

Any suggestions?

Regards,

Joe

**Comment by sei-dupdyke** [comment]
Hi, sorry about this, it is an issue with Auto-IT and I think we are seeing this elsewhere. I am looking for a more permanent fix, but in the meantime, please checkout this regedit fix:

https://stackoverflow.com/questions/14644258/how-to-get-autoit-reference-working-in-c

**Comment by joe-thompson-exa** [comment]
@sei-dupdyke,

Thanks for that! I had to install autoit first to create the registry entries then added the blank string as described in that link and works fine.

Regards,

Joe

**Comment by clenk** [comment]
I ran into the same problem and was able to solve it by registering the DLLs:
```
regsvr32 bin/debug/AutoItX3.dll
regsvr32 bin/debug/AutoItX3_64.dll
```
