### ISSUE TITLE
Outlook handler text encoding

### ISSUE THREAD

**Issue by vydrazde** [cmu-sei/GHOSTS#216]
When using either Outlook handler, text encoding breaks for non-ASCII characters. I could not figure out which encoding ghosts expects.

I used `email-content.csv` with UTF-8
```
1|test tři čtyři pět|\n\n\ntest tři čtyři pět
```

And got 
```
2023/05/29 12:41:26.933|Ghosts.Client.Handlers.Outlookv2.SendEmailViaOutlook|Setting message subject to: test tÃ…â„¢i Ã„ÂtyÃ…â„¢i pÃ„â€ºt
2023/05/29 12:41:26.955|Ghosts.Client.Handlers.Outlookv2.SendEmailViaOutlook|Setting message Body to: test tÃ…â„¢i Ã„ÂtyÃ…â„¢i pÃ„â€ºt
```

**Comment by sei-dupdyke** [comment]
(Disclaimer: Encoding is not my strong suit)

The client application throughout should be UTF-8 (and IIRC this is the .net default). Any comparisons of strings should be using `StringComparison.InvariantCultureIgnoreCase` to ignore culture-specific comparison errors.

Stepping through the debugger, we see:

![Screenshot 2023-06-01 at 6 56 27 PM](https://github.com/cmu-sei/GHOSTS/assets/43444464/8c4ebdb0-e8da-4a02-81e4-67dfcdcc7a22)

![Screenshot 2023-06-01 at 6 57 15 PM](https://github.com/cmu-sei/GHOSTS/assets/43444464/33eb633a-e585-4c19-85a4-95d1216dd15c)

The Outlook message appears to be OK:

![Screenshot 2023-06-01 at 7 09 07 PM](https://github.com/cmu-sei/GHOSTS/assets/43444464/e938ab1b-fede-40a0-842d-ab863b312f19)

The logs also look fine:

![Screenshot 2023-06-01 at 7 12 19 PM](https://github.com/cmu-sei/GHOSTS/assets/43444464/4320e892-d787-4162-821a-b1a1fad75af8)

![Screenshot 2023-06-01 at 7 12 46 PM](https://github.com/cmu-sei/GHOSTS/assets/43444464/df411018-584b-4d00-843a-71877c216bcd)

So, I wonder if this is a display error particular to your environment or with the app that you are using to view the logs with?

**Comment by vydrazde** [comment]
I used notepad.exe to open both `email-content.csv` and `app.log`. Both show UTF-8, yet in `email-contet.csv` all is well and in `app.log` the encoding is broken. The emails in Outlook have broken encoding as well, even when I explicitly set encoding to UTF-8 in Outlook.

I thought that the issue lies in Ghosts, since I saw it broken in logs before it was sent to Outlook, hence I created this issue. But since it is working for you, there must be something wrong with my setup, so I will dig deeper. I will post the results once I find the culprit.

Thanks for looking into this!

**Comment by sei-dupdyke** [comment]
Hmm, what is your system encodings or "character set" set to?

**Comment by vydrazde** [comment]
That's it! It was `Western European (Windows)`
```powershell
PS C:\Users\exercise> [System.Text.Encoding]::Default

IsSingleByte      : True
BodyName          : iso-8859-1
EncodingName      : Western European (Windows)
HeaderName        : Windows-1252
WebName           : Windows-1252
WindowsCodePage   : 1252
IsBrowserDisplay  : True
IsBrowserSave     : True
IsMailNewsDisplay : True
IsMailNewsSave    : True
EncoderFallback   : System.Text.InternalEncoderBestFitFallback
DecoderFallback   : System.Text.InternalDecoderBestFitFallback
IsReadOnly        : True
CodePage          : 1252
```

After changing it using https://techcommunity.microsoft.com/t5/windows-10/windows-10-1903-how-to-change-default-encoding-utf-8-to-ansi-in/m-p/2710604/highlight/true#M7410

```powershell
PS C:\Users\exercise> [System.Text.Encoding]::Default

BodyName          : utf-8
EncodingName      : Unicode (UTF-8)
HeaderName        : utf-8
WebName           : utf-8
WindowsCodePage   : 1200
IsBrowserDisplay  : True
IsBrowserSave     : True
IsMailNewsDisplay : True
IsMailNewsSave    : True
IsSingleByte      : False
EncoderFallback   : System.Text.EncoderReplacementFallback
DecoderFallback   : System.Text.DecoderReplacementFallback
IsReadOnly        : True
CodePage          : 65001
```
The emails get sent correctly! So it seems the `[System.Text.Encoding]::Default` property gets used. 

And I found another, IMO better solution. By adding BOM (Byte Order Mark) to the start of the file - `\xEF\xBB\xBF` for UTF-8, the encoding gets selected properly without changing the Default.

Thanks a lot for the help!
