### ISSUE TITLE
Feature Request: Change email footer

### ISSUE THREAD

**Issue by vydrazde** [cmu-sei/GHOSTS#217]
Currently the folowing text gets added to each message as per https://github.com/cmu-sei/GHOSTS/blob/master/src/Ghosts.Client/Infrastructure/Email/EmailConfiguration.cs#L96:
```
{Environment.NewLine}{Environment.NewLine}CONFIDENTIALITY NOTICE: This e-mail message, including any attachments, may contain information that is protected by the DoD Privacy Act. This e-mail transmission is intended solely for the addressee(s). If you are not the intended recipient, you are hereby notified that you are not authorized to read, print, retain, copy, disclose, distribute, or use this message, any part of it, or any attachments. If you have received this message in error, please immediately notify the sender by telephone or return e-mail and delete this message and any attachments from your system without reading or saving in any manner. You can obtain additional information about the DoD Privacy Act at http://dpclo.defense.gov/privacy. Thank you.{Environment.NewLine}Timestamp: {DateTime.Now} ID: {this.Id}";
```

It would be great if there was an option to change this footer, possibly with placeholders for Timestamp and ID, to create a footer which is not from DoD. Ideally even a placeholder for current user name to be able to sign the emails as the current user.

**Comment by sei-dupdyke** [comment]
I did a basic template for this, so in `config/emails-footer.txt` you can reformat however you like. It currently supports:

{{from}}
{{now}}
{{id}}

But I can certainly add more in the future, just LMK what they should be.

If that config file is not there, then the old footer is used.

This is available right now with the current client version 7.0.132.

Thanks for the good suggestion!!

**Comment by vydrazde** [comment]
Awesome, thanks for the lightning fast implementation!
