### ISSUE TITLE
manifest for dustinupdyke/ghosts:7.0.40 not found: manifest unknown

### ISSUE THREAD

**Issue by Ugo-SAM** [cmu-sei/GHOSTS#221]
When I run "docker compose up -d" I get this error:
"manifest for dustinupdyke/ghosts:7.0.40 not found: manifest unknown"
I'm using the docker-compose.yml from this site here, insisde the yml is the reference to this image.
  ghosts-api:
    image: dustinupdyke/ghosts:7.0.40
    
To me as a not experienced user (and after looking up lots of sites regarding such error) looks like this image doesn't exist?
 Docker info shows "Registry: https://index.docker.io/v1/"
 Or am I doing someting wrong? I'm using a fresh Alpine Linux V3.18.
Thank you.

**Comment by sei-dupdyke** [comment]
This has been pushed, sorry about the confusion. 

There is a slightly newer one as well 7.0.50 you might use too.

**Comment by Ugo-SAM** [comment]
> This has been pushed, sorry about the confusion.
> 
> There is a slightly newer one as well 7.0.50 you might use too.

I changed to 7.0.50 in the yml and it installs.
Thank you for the quick solution!
