### ISSUE TITLE
Missing documentation - CMU Core

### ISSUE THREAD

**Issue by jakobjohns** [cmu-sei/GHOSTS#228]
Just noticed that the github pages that is hosted on here is missing a plethora of information regarding configuration and what not. Not sure if this was accidentally removed and an older commit sufficed, but would love an update if possible. Thank you!

**Comment by sei-dupdyke** [comment]
Hi. I don't see any changes in the doc directory for months — what content is missing?

**Comment by DanPiMan** [comment]
I don't mean to talk on behalf of jakobjohns, but I have also noticed what seems to be missing information. Under Ghost Documentation>Core Client>Client Handlers, most of the client handlers are empty, such as Cmd, Clicks, Watcher, Office, NPCSystem, and others. Again, not sure what jakobjohns was referring to, but this is what I have noticed in my journey to installing and configuring the GHOSTS client.

**Comment by sei-dupdyke** [comment]
Ah, but that's always been missing 😉 

Sorry, I haven't gotten to those sections yet, and due to a lack of funding this summer, I haven't been able to set aside time to work on those sections. I'll try to make some progress knowing that y'all are looking for those sections to be completed, sorry.

**Comment by sei-dupdyke** [comment]
First draft of those sections is out there, lmk if something isn't crystal.

**Comment by jakobjohns** [comment]
Appreciate it @sei-dupdyke , means a bunch.
