### ISSUE TITLE
Mismatched method call and signature for `Report` on `Cmd` Handler results in output data ending up in `commandarg` on database.

### ISSUE THREAD

**Issue by lightfoot256** [cmu-sei/GHOSTS#234]
In the `Ghosts.Client.Handlers.Cmd` class; in the `Command` method; on line `116` there is a call to `Report` which has 4 arguments:
```c#
this.Report(handler.HandlerType.ToString(), command, outputString, timelineEvent.TrackableId);
```

In the `Ghosts.Client.Handlers.BaseHandler` super class; the available method signatures are:

```c#
        public void Report(string handler, string command, string arg)
        public void Report(string handler, string command, string arg, string trackable)
        public void Report(string handler, string command, string arg, string trackable, string result)
```

With only the middle having 4 arguments; Because of this; middle method is chosen resulting in the output string being sent as the `arg` instead of using the last method to send the output in the `result` variable instead.

I assumed `CommandArgs` was used to send arguments to the command but it appears to be used as an addition to sending multiple commands after the first one and is passed into the report function as a command -- in which case the `arg` string in report seems redundant since they're all just commands...

Other handlers like `Click` just pass an emptry string for the arg field

Thanks,
Chris

**Comment by lightfoot256** [comment]
Again; was looking in the wrong place; linux uses the Bash handler instead; but the call to `Report` is still mismatched:

```c#
            Report(HandlerType.Command.ToString(), escapedArgs, this.Result);
```

Should probably be something like:

```c#
            Report(HandlerType.Command.ToString(), escapedArgs, "", "", this.Result);
```

**Comment by sei-dupdyke** [comment]
Yikes, thanks for finding this — I will fix ASAP 👍

**Comment by sei-dupdyke** [comment]
v7.0.220.0 now available with these changes. I got rid of the overrides in report and replaced it with a first class object. Thanks for submitting this with all the needed details, appreciate it!
