### ISSUE TITLE
Linux Client - no action/activity being performed

### ISSUE THREAD

**Issue by dssangan** [cmu-sei/GHOSTS#236]
Hello, I'm a noob in this relam. Background in computer science, so have little understanding on what is happening in this project. It seems like a very cool project and I'm looking to explore more. I have hit a small blocker and need some help.

I have recently setup the Ghosts 7.0 client on an Ubunutu 22.04 VM, running .net 6.0. I am able to run the client, but it doesn't perform any activity as instructed in the timeline config. I have downloaded the windows client on a windows machine and tested it there. It works completely fine, is there something I'm doing incorrectly for linux client version?

Config file: ![image](https://github.com/cmu-sei/GHOSTS/assets/32006591/d877a26d-036f-4511-991e-a4daf73185bc)
Running ghost client in linux: 
![image](https://github.com/cmu-sei/GHOSTS/assets/32006591/f2b4a2c1-c25f-4af0-b44d-94d5d919bef8)

I have seen some articles & issues in this repo, most of them had client ran on windows and API on linux. Is that the standard practice?

TIA for all the advice and help.

**Comment by sei-dupdyke** [comment]
Thanks for checking out the project. What handler are you using? If its Firefox or Chrome, do you have the corresponding chrome or geckodriver binaries?

**Comment by dssangan** [comment]
I downloaded the firefox gecodriver from here: https://github.com/mozilla/geckodriver/releases and placed it in the same directory as client file. 

I have tried the firefox activity in the config and I get the following error. So I tried using the commandline commans in the config file to be executed
![image](https://github.com/cmu-sei/GHOSTS/assets/32006591/5d227312-07aa-4820-9e4d-2cbd5a228991)


![image](https://github.com/cmu-sei/GHOSTS/assets/32006591/d2698d48-18ff-4d97-a4e3-fb1c1dedc56e)

**Comment by sei-dupdyke** [comment]
Hmm, that's a new one.

What version of FF? What version of geckodriver?
Can you run FF directly without issue?

**Comment by dssangan** [comment]
I think it's the latest version of firefox:
![image](https://github.com/cmu-sei/GHOSTS/assets/32006591/9c2ca029-2175-4d93-b22c-32353df7e7b6)

For geckodriver, i'm utilizing the most recent version: 
![image](https://github.com/cmu-sei/GHOSTS/assets/32006591/38b5dcae-95eb-4ea7-a947-8d75c280f82c)

**Comment by sei-dupdyke** [comment]
Can you try running the geckodriver binary manually and see if it fires up without issue please?

**Comment by dssangan** [comment]
![image](https://github.com/cmu-sei/GHOSTS/assets/32006591/8ddbdb32-0557-4e0a-b5da-62ce2326bbba)
As I mentioned I'm kinda noob with all these, but I hope this helps

**Comment by sei-dupdyke** [comment]
Hmm looks like it (or something else is running on that port), do you mind trying this:

`ps aux | grep geckodriver`
see the PID
`kill $whatever_the_PID_is`

and try to run geckodriver again please?

**Comment by dssangan** [comment]
It showed there were two processes, I was able to kill the first one but second one kept auto-running. Ran the geckodriver again and this is the result:
![image](https://github.com/cmu-sei/GHOSTS/assets/32006591/a95e4934-949b-4552-a173-6291ec3e7617)

**Comment by sei-dupdyke** [comment]
Hmm, using v33 of geckodriver, and FF version 117, everything works fine from here — are you putting geckodriver in the same folder as the ghosts binary?

**Comment by dssangan** [comment]
Yeah they are in the same directory, I had also downloaded the chrome driver and unzipped it there as well (you can see many other files due that reason in the folder):
![image](https://github.com/cmu-sei/GHOSTS/assets/32006591/b74fd7b7-d8a6-4f44-9136-0472179fa245)

**Comment by dssangan** [comment]
Could you guide me about my timeline config file on why it is not running the commands in command line?
![image](https://github.com/cmu-sei/GHOSTS/assets/32006591/b402d568-b8c0-4424-bfe6-2064a36cb960)

**Comment by sei-dupdyke** [comment]
If it is not running at all (as I understood it at the beginning of this issue) I would just use the default timeline until that works, otherwise, we will be conflating issues or perhaps creating new ones, while the original remains unresolved.

**Comment by sei-dupdyke** [comment]
I see you have a logs folder, what does logs/application.log say?

**Comment by dssangan** [comment]
![image](https://github.com/cmu-sei/GHOSTS/assets/32006591/6efcb9b2-6ac4-460b-85ba-d5480b1fed1e)

**Comment by sei-dupdyke** [comment]
I'm confused. The logs indicate that it executed commands correctly. What is in the other log file?

**Comment by dssangan** [comment]
![image](https://github.com/cmu-sei/GHOSTS/assets/32006591/7758a108-47e4-413c-886d-e58b31820ed5)
It should open a command terminal and should leave it open correct? 

And as you can see, it hasn't created a new directory that I have provided in my command args above

**Comment by sei-dupdyke** [comment]
Without an absolute path, I'm not sure that's where it would have created that folder. It would have been where the shell spawn default location would be...

**Comment by dssangan** [comment]
Yeah that's my bad, I forgot to add the change directory command to downloads. But default terminal gets spawned at ./home directory.

![image](https://github.com/cmu-sei/GHOSTS/assets/32006591/22e75f36-aff8-4e5c-b3cb-f679cb462493)

**Comment by dssangan** [comment]
[1680f0e9-4547-4872-8506-8c01334f4e99.log.log.log.log.log](https://github.com/cmu-sei/GHOSTS/files/12729391/1680f0e9-4547-4872-8506-8c01334f4e99.log.log.log.log.log)
[app.log](https://github.com/cmu-sei/GHOSTS/files/12729393/app.log)

Attaching the log files from the VM here for review

**Comment by sei-dupdyke** [comment]
Try this

```json
{
  "Status": "Run",
  "TimeLineHandlers": [
    {
      "HandlerType": "Command",
      "Initial": "bash",
      "UtcTimeOn": "00:00:00",
      "UtcTimeOff": "24:00:00",
      "Loop": "True",
      "TimeLineEvents": [
        {
          "Command": " mkdir /tmp/bleep",
          "CommandArgs": [
            "pwd",
            "ls"
          ],
          "DelayAfter": 15000,
          "DelayBefore": 0
        }
      ]
    }
  ]
}
```

**Comment by dssangan** [comment]
I see. I just checked the directory that was mentioned in the timeline config you provided. And it did create that bleep folder! Is there anyway for me to keep that a terminal open that executes this command?

**Comment by dssangan** [comment]
@sei-dupdyke any recommendations for this?

> I see. I just checked the directory that was mentioned in the timeline config you provided. And it did create that bleep folder! Is there anyway for me to keep that a terminal open that executes this command?

**Comment by sei-dupdyke** [comment]
For Linux, not off the top of my head sorry. I'm further hamstrung by computer problems this week. I will look at this though when I get back onto a stable environment.

**Comment by dssangan** [comment]
Would you like me to keep this open or close it? I have got a good head start thanks to all your help so far :)

**Comment by sei-dupdyke** [comment]
Yes, let's please keep it open and I will dig into the bash handler to either see if keeping the window open is already possible or if i can add that function in... Thanks for your patience.

**Comment by dssangan** [comment]
For some reason change directory command isn't working. I am using this config file that will create the directory in the folder where the ghost client is being executed from.
![image](https://github.com/cmu-sei/GHOSTS/assets/32006591/e7fc0212-95c4-4816-bf2c-b7e1ddc1f28a)

But if I change directory to go back one directory and try to create that directory there, no results there. Wondering if cd command doesn't work or something
![image](https://github.com/cmu-sei/GHOSTS/assets/32006591/67870013-fee9-4431-95f9-bc457cb57306)

**Comment by rupeshrrts** [comment]
{
  "Id": "c089247f-32ce-4ae1-b3e9-07eff664c82b",
  "Status": "Run",
  "TimeLineHandlers": [
    {
      "HandlerType": "Word",
      "Initial": "",
      "UtcTimeOn": "00:00:00",
      "UtcTimeOff": "24.00:00:00",
      "UtcTimeBlocks": null,
      "HandlerArgs": {},
      "Loop": true,
      "TimeLineEvents": [
        {
          "TrackableId": null,
          "Command": "create",
          "CommandArgs": [
            "c:\\Users\\rkrrt\\OneDrive\\Documents"
          ],
          "DelayAfter": 900000,
          "DelayBefore": 0
        }
      ],
      "ScheduleType": "Other",
      "Schedule": null
    },
    {
      "HandlerType": "Excel",
      "Initial": "",
      "UtcTimeOn": "00:00:00",
      "UtcTimeOff": "24.00:00:00",
      "UtcTimeBlocks": null,
      "HandlerArgs": {},
      "Loop": true,
      "TimeLineEvents": [
        {
          "TrackableId": null,
          "Command": "create",
          "CommandArgs": [
            "c:\\Users\\rkrrt\\OneDrive\\Documents"
          ],
          "DelayAfter": 900000,
          "DelayBefore": 0
        }
      ],
      "ScheduleType": "Other",
      "Schedule": null
    },
    {
      "HandlerType": "PowerPoint",
      "Initial": "",
      "UtcTimeOn": "00:00:00",
      "UtcTimeOff": "24.00:00:00",
      "UtcTimeBlocks": null,
      "HandlerArgs": {},
      "Loop": true,
      "TimeLineEvents": [
        {
          "TrackableId": null,
          "Command": "create",
          "CommandArgs": [
            "c:\\Users\\rkrrt\\OneDrive\\Documents"
          ],
          "DelayAfter": 900000,
          "DelayBefore": 0
        }
      ],
      "ScheduleType": "Other",
      "Schedule": null
    },
    {
      "HandlerType": "BrowserChrome",
      "Initial": "about:external",
      "UtcTimeOn": "00:00:00",
      "UtcTimeOff": "24.00:00:00",
      "UtcTimeBlocks": null,
      "HandlerArgs": {},
      "Loop": true,
      "TimeLineEvents": [
        {
          "TrackableId": null,
          "Command": "random",
          "CommandArgs": [
            "http://iitjammu.ac.in",
	    "http://iitb.ac.in",
	    "http://iitd.ac.in",
	    "http://iitk.ac.in"
          ],
          "DelayAfter": 1000,
          "DelayBefore": 0
        }
      ],
      "ScheduleType": "Other",
      "Schedule": null
    },
    {
      "HandlerType": "BrowserChrome",
      "Initial": "about:internal",
      "UtcTimeOn": "00:00:00",
      "UtcTimeOff": "24.00:00:00",
      "UtcTimeBlocks": null,
      "HandlerArgs": {},
      "Loop": true,
      "TimeLineEvents": [
        {
          "TrackableId": null,
          "Command": "random",
          "CommandArgs": [
            "https://iitjammu.ac.in",
            "https://iitb.ac.in",
            "https://iitd.ac.in"
          ],
          "DelayAfter": 900000,
          "DelayBefore": 0
        }
      ],
      "ScheduleType": "Other",
      "Schedule": null
    }
  ]
}

**Comment by rupeshrrts** [comment]
Above this timelime.json file for windows is correctly working  like creating word file, excell file and also powerpoint files on a specific location . So for generating same in Ubuntu what I need to changes in thid code ?
