### ISSUE TITLE
Installing the Server API via Docker

### ISSUE THREAD

**Issue by spctravis** [cmu-sei/GHOSTS#24]
I am having issues trying to get the Server up and working on Ubuntu 18.04.
Running this command has some errors: $ docker build . -t ghosts/api --no-cache -f dockerfile-api
1. There is no dockerfile-api file so I used the file found in  Ghosts.Api folder called dockerfile
It would then run but get stuck on step 2/8
2. It could not copy bin/publish/. /app/ from line 25 of your dockerfile
I did a interactive terminal into the microsoft/dotnet and could not find bin/publish, but I don't know what you are trying to pull from the microsoft/dotnet docker image

**Comment by sei-dupdyke** [comment]
Installing from the prebuilt binaries is an easier option if you just want to get up and running quickly: https://github.com/cmu-sei/GHOSTS/wiki/Installation-from-distribution-binaries

**Comment by sei-dupdyke** [comment]
Let me know if you have any further difficulties or questions, otherwise closing this for now.
