### ISSUE TITLE
outlook attachment

### ISSUE THREAD

**Issue by jtwilco2** [cmu-sei/GHOSTS#240]
Using the Windows Client. What is the JSON looking for outlook and attachments? I assumed it was a file path but is not working. I was able to get the client to send an email without attachment.

{
  "Id": "b3d2e5c4-c035-40f5-a05f-5a3a32621ec8",
  "Status": "Run",
  "TimeLineHandlers": [
    {
      "HandlerType": "Outlook",
      "Initial": "",
      "UtcTimeOn": "00:00:00",
      "UtcTimeOff": "24.00:00:00",
      "HandlerArgs": {},
      "Loop": false,
      "TimeLineEvents": [
        {
          "TrackableId": null,
          "Command": "create",
          "CommandArgs": [
            "CurrentUser",
            "Random|Other:string ToEmailAddress - ******@gmail.com",
            "Random|Other:string CcEmailAddress - ******@gmail.com",
            "Random|Other:string BccEmailAddress - ******@gmail.com",
            "Random|Other:string Hello from Ghosts",
            "Random|Other:string Testing to see if this works!",
            "PlainText|RTF|HTML enum BodyType",
            "string Attachments - C:\Users\******\Downloads\file.docx"
          ],
          "DelayAfter": 900000,
          "DelayBefore": 0
        }
      ],
      "ScheduleType": "Other",
      "Schedule": null
    }
  ]
}

**Comment by jtwilco2** [comment]
Thank you for the quick response. That got the outlook command working again, but the log says it cannot find the file.

2023/10/23 19:16:48.893|Ghosts.Client.Infrastructure.Email.EmailConfiguration..ctor|Can't add attachment string Attachments - C:\Users\******\Downloads\Capture.JPG - file was not found

I copy and pasted the location as seen above in the log into file explorer and the image came right up. So the file path is correct but ghosts is not finding it. Any suggestions?

**Comment by sei-dupdyke** [comment]
Hmm, that looks correct, let me do some debugging on my side. Standby please.

**Comment by sei-dupdyke** [comment]
Hmm, this seems to work fine for me:
![image](https://github.com/cmu-sei/GHOSTS/assets/43444464/874b8fc4-0676-4c52-9ee8-66e0f6fac760)

What version of GHOSTS and Outlook are you using?

**Comment by sei-dupdyke** [comment]
Also, do you see anything in logs/application.log related to outlook please?
