### ISSUE TITLE
Can't find ghosts.exe file

### ISSUE THREAD

**Issue by ramenoods** [cmu-sei/GHOSTS#26]
Can't find the ghosts.exe file in the ghosts folder found in this link: https://cmu.app.box.com/s/5a14hejyimobortilxierppq6zr855kd

I followed the instructions for installing a Linux Ghosts client from here: https://github.com/cmu-sei/GHOSTS/wiki/Installation-from-distribution-binaries

Once I open the folder that I just downloaded (from the first link I provided), I am supposed to execute the ghosts.exe file. I cannot find this file.

**Comment by sei-dupdyke** [comment]
Hi, on linux the file will be a binary that you will need to execute via dotnet (which is a dependency you'll need to install first). The command would be `dotnet run ghosts.client.linux.dll`.

**Comment by rodrilp** [comment]
Hi!

I get an error when I run the command.
In the console appears: "No project could be found to implement"

**Comment by sei-dupdyke** [comment]
Ah, sorry, try just `dotnet ghosts.client.linux.dll` — you don't need the run. Sorry for the confusion.

**Comment by rodrilp** [comment]
Oh yes!! Thanks!!
