### ISSUE TITLE
Grafana keeps stopping

### ISSUE THREAD

**Issue by configmanCooper** [cmu-sei/GHOSTS#262]
I know there is documentation about chowning g_data but I have done that

I'm in the latest version of Ubuntu
The error I'm getting is as follows:

(HTTP code 500) server error - error while creating mount source path '/host_mnt/home/configuration/grafa/datasources': mkdir /host_mnt/home/configuration: permission denied

Thanks

**Comment by sei-dupdyke** [comment]
dupe of #263
