### ISSUE TITLE
Issue of document creation in ubuntu similarly as created in ubuntu by ghosts.

### ISSUE THREAD

**Issue by rupeshrrts** [cmu-sei/GHOSTS#264]
![Untitled](https://github.com/cmu-sei/GHOSTS/assets/90381910/383a5acc-0613-44d5-b9ed-253d00209c04)

In windows documents created by this command in word but if I want to create same in Ubuntu. I tried multiple ways to do this but not created successfull. how can I do this?

**Comment by sei-dupdyke** [comment]
Hi, thanks for checking out the project!

The Office handlers (Word, Excel, PowerPoint, Outlook) are not applicable to Ubuntu, because there is no Office install for that OS. The client will simply ignore these handlers if configured.
