### ISSUE TITLE
Problem with ghost api server, I can’t get information about surveys activities or timelines.

### ISSUE THREAD

**Issue by didiqu** [cmu-sei/GHOSTS#273]
Hello i have a problem with ghost client feedback in ghost api-server.

I have deployed ghost api server with docker, and i have a ghost client on windows 10 Pro version 19045
This is my application.json file on the client
```json
{
    "IdEnabled": true,
    "IdUrl": "http://XXX.XXX.XXX.XXX:5000/api/clientid",
    "IdFormat": "guestlocal",
    "IdFormatKey": "guestinfo.id",
    "IdFormatValue": "$formatkeyvalue$-$machinename$",
    "VMWareToolsLocation": "C:\\progra~1\\VMware\\VMware Tools\\vmtoolsd.exe",
    "AllowMultipleInstances": false,
    "EncodeHeaders": true,
    "ClientResults": {
        "IsEnabled": true,
        "IsSecure": false,
        "PostUrl": "http://XXX.XXX.XXX.XXX:5000/api/clientresults",
        "CycleSleep": 300000
    },
    "ClientUpdates": {
        "IsEnabled": true,
        "PostUrl": "http://XXX.XXX.XXX.XXX:5000/api/clientupdates",
        "CycleSleep": 300000
    },
    "Survey": {
        "IsEnabled": true,
        "IsSecure": false,
        "Frequency": "once",
        "CycleSleepMinutes": 5,
        "OutputFormat": "indent",
        "PostUrl": "http://XXX.XXX.XXX.XXX:5000/api/clientsurvey"
    },
    "TimelineConfiguration": {
        "Location": "config/timeline.json",
        "useThisToDownloadInitialTimelineFromALocation": "https://raw.githubusercontent.com/cmu-sei/GHOSTS/6e04885809dfdceb138fbf9cdf1a1f795ea907ef/src/Ghosts.Client/config/timeline.json"
    },
    "Content": {
        "EmailsMax":  20,
        "EmailContent": "",
        "EmailReply": "",
        "EmailDomain": "",
        "EmailOutside": "",
        "BlogContent": "",
        "BlogReply": "",
        "FileNames": "",
        "Dictionary": ""
    },
    "ResourceControl": {
        "ManageProcesses": true
    },
    "HealthIsEnabled": true,
    "HandlersIsEnabled": true,
    "DisableStartup": false,
    "ChromeExtensions": "",
    "FirefoxInstallLocation": "",
    "FirefoxMajorVersionMinimum": 48,
    "OfficeDocsMaxAgeInHours": 72,
    "Email": {
        "RecipientsToMin": 1,
        "RecipientsToMax": 3,
        "RecipientsCcMin": 0,
        "RecipientsCcMax": 2,
        "RecipientsBccMin": 2,
        "RecipientsBccMax": 2,
        "RecipientsOutsideMin": 0,
        "RecipientsOutsideMax": 1,
        "SetAccountFromConfig": false,
        "SetAccountFromLocal": false,
        "SetForcedSendReceive": true,
        "SaveToOutbox": false,
        "EmailDomainSearchString": "Get-ADUser -filter * -searchbase \"CN=USERS,DC=JRSS,DC=GOV\" -properties UserPrincipalName | select -expand UserPrincipalName"
    },
    "Listener": {
        "Port": -1
    },
    "AwsCli": {
        "InstallFolder": "%USERPROFILE%\\Amazon\\AWSCLIV2"
    },
    "EmailContent": {
        "conflict_1_capital": "",
        "conflict_1_name": "",
        "conflict_1_peoples": "",
        "conflict_1_president": "",
        "localized_flashpoint_locale": "",
        "friendly_nation_leader_lastname": "",
        "friendly_nation_leader_name": "",
        "friendly_nation_name": "",
        "friendly_nation_peoples": "",
        "commander_title": "",
        "commander_name": "",
        "commander_initials": "",
        "commander_lastname": "",
        "commander_email": "",
        "commander_sub1": "",
        "commander_sub2": "",
        "us_president": "",
        "iraq": "",
        "iraqi": "",
        "iran": "",
        "iranian": "",
        "china": "",
        "chinese": "",
        "russia": "",
        "azerbaijan": "",
        "turkish": "",
        "turkey": "",
        "pakistani": "",
        "pakistan": "",
        "palestinian": "",
        "palestine": "",
        "gaza": "",
        "korea": ""
    }
}
```
and the timeline.json is:
```json
{
    "machineId": "304dd882-ac81-43c6-8fbb-290c03ab1216",
    "type": 0,
    "activeUtc": "2024-02-16T15:56:30.097Z",
    "status": 0,
    "update": {
        "id": "05648ca6-2a19-4af1-9ff6-239c3349dca4",
        "status": 0,
        "timeLineHandlers": [
            {
                "HandlerType": "Notepad",
                "HandlerArgs": {
                    "execution-probability": 100,
                    "deletion-probability": 0,
                    "view-probability": 0,
                    "creation-probability": 0,
                    "modification-probability": 100,
                    "pdf-probability": 100,
                    "input-directory": "C:\\Users\\Administrateur",
                    "output-directory": "C:\\Users\\Administrateur",
                    "text-generation": "random",
                    "min-paragraphs": 4,
                    "max-paragraphs": 15,
                    "delay-jitter": 50
                },
                "Initial": "",
                "UtcTimeOn": "00:00:00",
                "UtcTimeOff": "24:00:00",
                "Loop": "True",
                "TimeLineEvents": [
                    {
                        "TrackableId": "1b8d74b9-13d1-42ab-966a-2bef553378ec",
                        "Command": "random",
                        "CommandArgs": [],
                        "DelayAfter": 20000,
                        "DelayBefore": 0
                    }
                ]
            }
        ]
    }
}
```

When i use the api server the following command works well:

api/home
with return:
```json
{
  "version": "7.0.0.0",
  "machines": 1,
  "groups": 1,
  "created": "2024-02-16T16:01:34.0015513Z"
}
```
/api/machines/list
with returns:
```json
[
  {
    "id": "304dd882-ac81-43c6-8fbb-290c03ab1216",
    "name": "ghost1net1000"
  }
]
```
but the following else does'nt work or doesn't return the the expected response
For example:
/timelines/304dd882-ac81-43c6-8fbb-290c03ab1216
return:
```json
[]
```
I can't get the timelines on the remote client with id: 304dd882-ac81-43c6-8fbb-290c03ab1216
I try to find informations in postgresql database with command: ```sql SELECT * FROM machine_timelines; ```
but have any result:
 id | machineid | timeline | createdutc 
----+-----------+----------+------------
(0 rows)

This is the same problem with surveys: /surveys/304dd882-ac81-43c6-8fbb-290c03ab1216
This is the same problem with machine activity: /api/machines/304dd882-ac81-43c6-8fbb-290c03ab1216/activity

The final question is how could we modify the application.json or timeline.json configuration to get information about timelines, trackable or machines information. Or perhaps another problem blocks another problem block ghost client’s feedback.

**Comment by sei-dupdyke** [comment]
Thanks for checking out the project.

I'm trying to get my development environment setup to replicate this, but its a bit of a switcharoo as I was working on a next version.

**Are there any errors in the client ./logs/application.log file?**

> Timelines on remote clients
But I did want to note that in v7, the clients have to check-in with the server in order to get that timeline — basically, you log a request for the timeline, and then the next time when that client checks in, it posts up what it has. This can take a while (I think the default is every 15 minutes IIRC). So, could it be the case that you looked in the db before the client got the instruction?

> Survey
Hmm, this should happen as soon as the agent starts up on a separate thread. Once it has the data, it posts this up to the server. I think this typically always happens within the first 5 minutes or so of agent start.

**Comment by didiqu** [comment]
About the waiting time of 5 or 15 minutes, i have waiting for it but nothing appear in the database or in the grafana view.
About timelines:
I don't know wich API command his used to send current timeline from client to api server. It' is /api/clienttimelines?
Because it's never used by the client when i try to find http network frame with wireshark.
So I guess I can change something in application.json to apply it.

The problem could it come from that i launch ghost command from ansible task?
Because to close the task i use an async task?
Is there a good way to run a ghost client from ansible?

Thank you!!

**Comment by sei-dupdyke** [comment]
> I don't know wich API command his used to send current timeline from client to api server. It' is /api/clienttimelines?

Negative, all the API endpoints that begin with client are only for the clients to use (ClientId, ClientResults, ClientSurvey, ClientTimeline, ClientUpdates). The one you want to use is MachineUpdates with a UpdateType of `20` (RequestForTimeline = 20).

> I find this error in ghosts api container: fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.Text.DecoderFallbackException: Unable to translate bytes [E9] at index 233 from specified code page to Unicode.
         at System.Text.DecoderExceptionFallb

> Bytes [E9] correspond to ascii value "é". In the network trame, it correspond to "Microsoft Corporation Tous droits réservés" My windows is the French version, it could be the reason of this error?

Hmm, I admit I have not tested with OS versions other than US/en, but dotnet (the language ghosts is written in typically handles unicode test just fine. Do you have an "é" character in any of your configuration files? If so I can easily test. If not, it will take more time to test correctly.

> The problem could it come from that i launch ghost command from ansible task? Because to close the task i use an async task? Is there a good way to run a ghost client from ansible?

As long as you run ghosts as the user on the machine that you are "bringing to life" it should not matter what launches the application. ghosts is not really meant to be run as the box administrator, and so there is not much testing in that model.

> Thank you!!

Thank you for your patience, hopefully we can work through these issues.

**Comment by didiqu** [comment]
![image](https://github.com/cmu-sei/GHOSTS/assets/24799192/91623a0c-ce6c-4d0c-91c2-ffd70800a166)
```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.Text.DecoderFallbackException: Unable to translate bytes [E9] at index 233 from specified code page to Unicode.
```
![image](https://github.com/cmu-sei/GHOSTS/assets/24799192/02127925-9a9f-4fb6-8b83-3c4e2a843743)

After more investigation with wireshark and ghosts-postgres container logs:
I think the bytes C3 E9 that correspond to letter é présent in the wireshark frame capture frame capture "Microsoft Corporation Tous droits réservés" when the Windows french version.

**Comment by sei-dupdyke** [comment]
Could you please get me a copy of ./logs/clientupdates.log from a client machine before it posts it up to the api? I can then easily test that from here (and hopefully fix).

This is surprising, "é" is a valid unicode character, and one of the big features of C# is its unicode support right out of the box!

**Comment by didiqu** [comment]
I don't understand why, because i haven't modify the content of the project. So i have no idea to resolve this error

**Comment by sei-dupdyke** [comment]
It looks like something before the command in that handler? If you view in a rich text editor can you see those ?-mark diamonds in the original timeline?

**Comment by sei-dupdyke** [comment]
A teammate helped me decode this, if you change the encoding to iso 8859-2 in vs code, it prints the characters:

![decoded](https://github.com/cmu-sei/GHOSTS/assets/43444464/cd0b7337-e623-48d0-b2fe-7b3bb50177b7)

**Comment by sei-dupdyke** [comment]
I have a work-around in v8 of the client (that I am working on) which strips out all-non ascii characters from the result field of the logs.

**Comment by didiqu** [comment]
Finally, the problem will be solved in GHOST v8? For the moment, I can use windows with US language?
Do you recommend a specific version?

**Comment by sei-dupdyke** [comment]
I have a fix already implemented in v8 for this, yes. I should have a release of that available very shortly, but here is a very early beta:

https://cmu.box.com/s/kqo5cl7f5f2v22xgud6o2fd26xrrwtpq

NOTE THAT THE CONFIG FILES ARE A NEW (but only slightly different) FORMAT. :)

Please let me know if this solves the issue if you are willing to give it a try.

**Comment by sei-dupdyke** [comment]
v8 is here.
