### ISSUE TITLE
Errors building from source on Windows using build script [with solution]

### ISSUE THREAD

**Issue by L015H4CK** [cmu-sei/GHOSTS#276]
Hello everyone,

the past weeks I have been working with GHOSTS and wanted to implement my own features, e.g. a new handler (more on this soon). Before I started the actual coding process, I tried to build GHOSTS from source and encountered some errors. I do not know if I made mistakes while doing so (I did not find any detailed documentation about it, only [this discussion thread](https://github.com/cmu-sei/GHOSTS/discussions/78)), but in any case I wanted to report the errors I encountered here:

First, when downloading and building GHOSTS using `scripts/build_windows.ps1` I encountered: 
`(...) Assets file (..)src\Ghosts.Domain\obj\project.assets.json not found. (...)`
Fix: `dotnet restore Ghosts.sln` in src directory. (This throws errors about ghosts.client.linux.csproj but I do not care about this at the moment...)

Then, rerunning the `build_windows.ps1` script:
`(...) error: Your project file doesn't list 'win-x64' as 'RuntimeIdentifier (...)'`
Fix: Adding `<RuntimeIdentifiers>win;win-x64</RuntimeIdentifiers>`, e.g. at line 5 (new line after `<PropertyGroup>`), to [`src\Ghosts.Client\Ghosts.Client.csproj`](https://github.com/cmu-sei/GHOSTS/blob/master/src/Ghosts.Client/Ghosts.Client.csproj#L5) and rerunning the above dotnet command fixed the errors for win and win-x64.

Again, I do not know if I made any mistakes or left out some important steps while building. This is also my first time working on a bigger project using C#. Just to make sure I want to reach out to you and check in about it. Maybe someone else will encounter these problems in the future.

Best regards,
L015

**Comment by sei-dupdyke** [comment]
Hi, thanks for checking out the project.

First issue, yes, you got it — I typically have already built and run from visual studio, so I neglected to put that step in the build scripts, sorry.

My configuration looks like this (I thought this was captured in the solution file?):

![image](https://github.com/cmu-sei/GHOSTS/assets/43444464/d8f9e8e6-a26b-40f1-9808-613bde9cc29a)

Release is basically the same as Debug.

**Comment by L015H4CK** [comment]
Hi and thank you for the swift response. To be honest I didn't try to build and run using visual studio and just stuck to the build script. I just built the x64 GHOSTS.Client successfully using Visual Studio. 

Do you want me to close the issue or keep it open for the build script related errors?
