### ISSUE TITLE
Help setting group timelines via API

### ISSUE THREAD

**Issue by pezhore** [cmu-sei/GHOSTS#278]
First off, great project - this has been a savior in the past, but I think the recent improvements made me lose grasp of how best to use it.

I'm trying to set two groups of NPCs on two different timelines. I've set the groups to the following:

```json
{
    "id": 20,
    "name": "generic_users",
    "groupMachines": [
        {
            "id": 1,
            "groupId": 20,
            "machineId": "fea44e90-c414-4330-b032-cea9adbf6eb1"
        },
        {
            "id": 7,
            "groupId": 20,
            "machineId": "2ce4de34-0e53-43b2-9d8f-a735392cdd2f"
        },
...
    ],
    "status": "Active",
    "machines": []
}
```

```json
{
    "id": 10,
    "name": "c2npcs",
    "groupMachines": [
        {
            "id": 63,
            "groupId": 10,
            "machineId": "064dbe43-5206-4077-865d-13e1d2a8f074"
        }
    ],
    "status": "Active",
    "machines": []
}
```

I'm trying to add the following timeline as a test (the test python script just hits a web site - I'll know it works if I see stuff pop in the logs.

```json
{
  "Status": "Run",
  "TimeLineHandlers": [
    {
      "HandlerType": "Command",
      "Initial": "bash",
      "UtcTimeOn": "00:00:00",
      "UtcTimeOff": "24:00:00",
      "Loop": "True",
      "TimeLineEvents": [
        {
          "Command": " python3 /opt/ghosts/client/test/test.py",
          "DelayAfter": 15000,
          "DelayBefore": 0
        }
      ]
    }
  ]
}
```

What I can't figure out is how to use the `http://ghosts-url/timelines/bygroup/:groupId` POST endpoint.

1. The swagger doc shows a `machineId` - what should that be set to if its the entire group?
2. `type` / `activeUtc` - can these be omitted?
3. `update` - I assume that is for the new timeline details?

Trying to run a post with the following gets me a NullReferenceException:

```json
{
  "machineId": "064dbe43-5206-4077-865d-13e1d2a8f074",
  "type": 10,
  "Status": "Run",
  "TimeLineHandlers": [
    {
      "HandlerType": "Command",
      "Initial": "bash",
      "UtcTimeOn": "00:00:00",
      "UtcTimeOff": "24:00:00",
      "Loop": "True",
      "TimeLineEvents": [
        {
          "Command": " python3 /opt/ghosts/client/test/test.py",
          "DelayAfter": 15000,
          "DelayBefore": 0
        }
      ]
    }
  ]
  }
}
```

Error:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ghosts.Api.Services.TimelineService.UpdateGroupAsync(Int32 groupId, MachineUpdateViewModel machineUpdateViewModel, CancellationToken ct)
   at ghosts.api.Controllers.TimelinesController.GroupTimeline(Int32 groupId, MachineUpdateViewModel machineUpdate, CancellationToken ct) in /app/Ghosts.Api/Controllers/TimelinesController.cs:line 92
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Accept: */*
Connection: Upgrade
Host: ghosts.mobile.range
User-Agent: PostmanRuntime/7.28.4
Accept-Encoding: gzip, deflate, br
Cache-Control: no-cache
Content-Type: application/json
Content-Length: 454
X-Real-IP: 192.168.49.173
X-Forwarded-For: 192.168.49.173
X-Forwarded-Proto: https
X-Nginx-Proxy: true
Postman-Token: a9dc89e4-1a86-4150-a2dc-6391d5109ccb```

**Comment by sei-dupdyke** [comment]
Thanks for the kind words. Hmm, I think it is a simple case of bad documentation:

![image](https://github.com/cmu-sei/GHOSTS/assets/43444464/b54a6614-6a68-4812-85aa-47b1dd99f164)

When I look in the code, I see ` /// <param name="groupId">Group Guid</param>` when the method signature is `GroupTimeline(int groupId`. I think if you simply pass the group integer, the method should function as you expect.

I'll clean this up in the next release, sorry about that.

**Comment by pezhore** [comment]
Thanks for the quick response! I just tried going with my target groupId (`10`), but I get the same error:

![image](https://github.com/cmu-sei/GHOSTS/assets/7430984/2e2b6fe4-9057-4738-8981-caee56c36240)

![image](https://github.com/cmu-sei/GHOSTS/assets/7430984/5c7f8a56-0741-4e86-8d55-e814db50b425)

**Comment by sei-dupdyke** [comment]
Ha, you beat me. The below is working for me — so I think something is missing in that payload you had that is required for the controller to know how to deserialize the json into an MachineUpdate object. There are a couple if I remove them, then the controller doesn't know what the payload is.

ActiveUtc is so the API knows when this update is in play (so that you could have activities planned for the future.

You should still be able to use 10 — that's probably the one you want (it means execute this right now, but leave the agent's original timeline as it is, "1" replaces the agent's default timeline! Here they are:

public enum UpdateType
{
    Timeline = 0,
    Health = 1,
    TimelinePartial = 10,
    RequestForTimeline = 20
}

Sorry for the way these work currently, I don't like the int payload and you having to look those values up, I'm just not sure how to change them to text.

```
{
  "type": "10",
  "activeUtc": "2024-03-02T15:39:18.691Z",
  "status": "Active",
  "update": {
    "type": 10,
    "Status": "Run",
    "TimeLineHandlers": [
      {
        "HandlerType": "Command",
        "Initial": "bash",
        "UtcTimeOn": "00:00:00",
        "UtcTimeOff": "24:00:00",
        "Loop": "True",
        "TimeLineEvents": [
          {
            "Command": "python3 /opt/ghosts/client/test/test.py",
            "CommandArgs": [],
            "TrackableId": "",
            "DelayAfter": 15000,
            "DelayBefore": 0
          }
        ]
      }
    ]
  }
}
```

**Comment by pezhore** [comment]
What's the best way to validate the timeline has been updated? Check on the target systems in the group? use the `/timelines/{machineId/` endpoint?

**Comment by pezhore** [comment]
Oh, that'll be nice!

For now, looking at a machine in the group that has the timeline above applied, I'm only seeing an empty set `[]` which doesn't make much sense given the timeline above should be active now.

![image](https://github.com/cmu-sei/GHOSTS/assets/7430984/aadcadca-7634-41c0-8201-cc1073f9b140)

Results for  `curl -X 'GET'  'https://ghosts.mobile.range/api/machinegroups/20'  -H 'accept: */*'`

```json
{
  "id": 20,
  "name": "generic_users",
  "groupMachines": [
    {
      "id": 1,
      "groupId": 20,
      "machineId": "fea44e90-c414-4330-b032-cea9adbf6eb1"
    },
...
    {
      "id": 45,
      "groupId": 20,
      "machineId": "807fa67f-ca56-4a29-a37f-0459af3a8052"
    },
   ...
  ],
  "status": "Active",
  "machines": []
}
```

**Comment by sei-dupdyke** [comment]
It may not have reported activity back yet?

On the timeline status, that would have to be by machines, I think — because when you apply a timeline to a group, essentially I deal those out to all the machines in the group immediately. Is that ok?

**Comment by pezhore** [comment]
That works for me. I wonder if something is up with my test python script that's causing the timeline to fail.

**Comment by sei-dupdyke** [comment]
Looking into this further — I think part of the problem across the board is that there are several endpoints that sort of blur functionality (including for me). One is this timeline controller was originally meant just to deal with default timelines, and the other being MachineUpdates, which can be 

```
Timeline = 0,
Health = 1,
TimelinePartial = 10,
RequestForTimeline = 20
```

So I moved the group one we'd been talking about and added a few lookup endpoints as well:

- by updateId (if you know it, and yes, I need to start returning these)
- by machineId
- by status (aka give me all the open ones, etc.)

![image](https://github.com/cmu-sei/GHOSTS/assets/43444464/dddb879e-bc5e-4bb0-942a-0afee62ca5b1)

Any others?

**Comment by pezhore** [comment]
Oh, I think that would work great. Any ideas when this would be released?

**Comment by sei-dupdyke** [comment]
v8 is here, should fix this issue.
