### ISSUE TITLE
Automated way to download the client

### ISSUE THREAD

**Issue by brahama** [cmu-sei/GHOSTS#279]
Hi! It would be really great to be able to download the client via curl to automate the provisioning for instance. CLient link currently seems complicated to automate.

Thanks!

**Comment by sei-dupdyke** [comment]
Thinking about how to implement this operationally — many installations of ghosts do not have access to the open internet, and so the client would most likely have to be baked into the API. I think I can automate this in the build of the API container...

Great idea though! I'm working on v8 currently, I'll see if I can't get this out with that version. Thank you!

**Comment by sei-dupdyke** [comment]
In v8 the current client binaries will be available from wherever you've installed the api, for example:

http://ghosts-api/install/client/windows  (which is the 64 bit version, but can use the below for specifics)
http://ghosts-api/install/client/windows/x64
http://ghosts-api/install/client/windows/x32
http://ghosts-api/install/client/windows/linux

**Comment by brahama** [comment]
Sweet.  will wait for v8 and see. Thanks!

**Comment by sei-dupdyke** [comment]
This is now available in v8 of the API! 🚀
