### ISSUE TITLE
Credentials for Swagger UI

### ISSUE THREAD

**Issue by playswithfir3** [cmu-sei/GHOSTS#30]
I'm trying to use the swagger ui, but I can't find the creds to auth. I've tried various combinations of scotty from the other creds that were used. 

Where are they configured? What are they?

Thanks!

**Comment by playswithfir3** [comment]
Alright, found it. But now I want to know what "http://localhost:59460/" is for, because I thought 5000 was the API?

**Comment by sei-dupdyke** [comment]
In the docker-compose file you can really expose it on any port. The reference to 59460 is a development leftover and is not currently used. Please ignore it.

**Comment by playswithfir3** [comment]
Thanks!
