### ISSUE TITLE
The GHOSTS 8.0 Linux Client linked on the quickstart page is compiled for ARM64

### ISSUE THREAD

**Issue by h0w1tzr** [cmu-sei/GHOSTS#308]
I tried running the Linux client, but it is compiled for ARM64:
![MicrosoftTeams-image](https://github.com/cmu-sei/GHOSTS/assets/42301701/0dc5d52e-1e84-4be6-8117-fa6e5b5e5175)

**Comment by sei-dupdyke** [comment]
Hi, sorry about that, I dealt with this for docker and it slipped my mind when I built the linux binaries recently.

I automated it with actions this morning, and updated them back to AMD. Should be good to go, sorry for the mistake.
