### ISSUE TITLE
GHOSTS do not wake on UtcTimeOn

### ISSUE THREAD

**Issue by vydrazde** [cmu-sei/GHOSTS#334]
In v8, the handlers are not run when sleeping and UtcTimeOn time passes. 

I was not able to debug this properly as I was not able to setup the local development environment, but I believe the issue is in [this loop](https://github.com/cmu-sei/GHOSTS/blob/master/src/Ghosts.Domain/Code/WorkingHours.cs#L41) (or the [loop above](https://github.com/cmu-sei/GHOSTS/blob/master/src/Ghosts.Domain/Code/WorkingHours.cs#L31))
```cs
var currentTime = DateTime.UtcNow.TimeOfDay;
...
while (currentTime < timeOn || currentTime > timeOff)
{
    Sleep(handler, 60000);
}
```
where the currentTime does not get updated within the loop, so it becomes stuck.

**Comment by sei-dupdyke** [comment]
Windows 8.0.14 should be out there as the default download. Thanks!!

**Comment by vydrazde** [comment]
OK, I have the Windows 8.0.14 version as per 
```
Info|Ghosts.Client.Infrastructure.DebugManager.Write|GHOSTS (ghosts:8.0.0.0 [8.0.14.0]) running in production mode
```
But in the logs I still see
```
Trace|Ghosts.Domain.Code.WorkingHours.Sleep|Ghosts.Domain.TimelineHandler sleeping for 60000 ms
```
repeatedly and the handler does not wake.
So either the build is not up-to-date or I have an older build and the version is not shown correctly?
The sha256 of my ghosts.exe is `E0B3280CAB5D299EE01EADCDDC987AE7FD69A09119C9DF59758BD09436990423`

**Comment by sei-dupdyke** [comment]
Ok, sorry about that, 8.0.16 is out there now and should fix the issue. #338

**Comment by vydrazde** [comment]
Yes, that works, thanks a lot!
