### ISSUE TITLE
socializer signalr server returned handshake error handshake was canceled

### ISSUE THREAD

**Issue by rbreesems** [cmu-sei/GHOSTS#341]
We are using the socializer docker container hosted on Centos 7.3 OS in our greyspace, and using the GHOSTS browser handler to browse to the page, do posts, click on links, etc with Firefox. We have socializer mapped to `www.tweeter.com`.

We are getting consistent javascript errors written to the console, I guess thrown by the Geckodriver, that is:
`www.tweeter.com/js/signalr.min.js, line 16: Error: Server returned handshake error: Handshake was canceled.`

I have googled around for this error, and it seems it may have something to do with websockets on the server not being enabled, but I don't know. Have you seen this error?  Other than polluting the console window output, it does not seem to be affecting operation.

**Comment by sei-dupdyke** [comment]
Hmm, have not seen it, but haven't been looking for it either - give me a bit to do some investigation. Thanks for reporting.

**Comment by sei-dupdyke** [comment]
Closing as no longer needed. Can reopen if needed.
