### ISSUE TITLE
socializer diskspace growth limiting

### ISSUE THREAD

**Issue by rbreesems** [cmu-sei/GHOSTS#342]
We are experimenting with socializer in our grayspace.  We are concerned about filling up available space in the socializer docker container.

After attaching to the socializer docker container and looking at files, it appears that growth is in:
/app/db/socializer.db-shm
/app/db/socializer.db-wal   (text posts?)

/app/wwwroot/images/*  (images uploaded with posts are stored here).

We have to implement some sort of disk-limiting before we can deploy to this a real event, and could hack something together, but are wondering if there is any near term plans to implement automated post pruning, perhaps all posts older than XX hours gets automatically deleted to free space. 

Thanks.

**Comment by sei-dupdyke** [comment]
I can build a cleanup hosted service, so you will configure how often it runs, and how old the stuff is that it deletes. — give me a day or two to publish a new container.

**Comment by sei-dupdyke** [comment]
Configuration file is [here](https://github.com/cmu-sei/GHOSTS/blob/master/src/ghosts.pandora.socializer/src/appsettings.json) - how often the job runs and how old things need to be before they are deleted are listed as separate configurations.

**Comment by rbreesems** [comment]
Thanks for this! We have pulled the new container and testing!
