### ISSUE TITLE
SSH handler does not respect UtcTimeOff

### ISSUE THREAD

**Issue by vydrazde** [cmu-sei/GHOSTS#346]
Once the SSH handler starts running, it does not turn off when `UtcTimeOff` passes.

It likely gets stuck in [this loop](https://github.com/cmu-sei/GHOSTS/blob/master/src/Ghosts.Client/Handlers/Ssh.cs#L144)

```c#
while (true)
{
    var cmd = timelineEvent.CommandArgs[_random.Next(0, timelineEvent.CommandArgs.Count)];
    if (!string.IsNullOrEmpty(cmd.ToString()))
    {
        this.Command(handler, timelineEvent, cmd.ToString());
    }
    Thread.Sleep(Jitter.JitterFactorDelay(timelineEvent.DelayAfterActual, jitterfactor)); ;
}
```

where `WorkingHours.Is(handler);` is not called. It could be called as the condition of the loop.

**Comment by rbreesems** [comment]
I will fix this in next PR from my branch.

**Comment by rbreesems** [comment]
Actually, the while(true) needs to be removed entirely as the `WorkingHours.Is(handler)` is called in the Ex function and the loop attribute will cause it to loop.

**Comment by rbreesems** [comment]
This is a problem with ftp, sftp, wmi also., will fix.

**Comment by rbreesems** [comment]
FYI, this was fixed in a PR that was merged yesterday.

**Comment by vydrazde** [comment]
Great! Could you make a new build so I can test this?

**Comment by rbreesems** [comment]
Dustin makes the builds so I am sure one will be done.

**Comment by vydrazde** [comment]
Thanks a lot! I can confirm that this is fixed.

**Comment by sei-dupdyke** [comment]
The power of the team on this one 💪 - thanks all.
