### ISSUE TITLE
Bootstrap Windows clients automatically to run GHOSTS client 

### ISSUE THREAD

**Issue by iknowjason** [cmu-sei/GHOSTS#357]
Are there any features or capabilities of the GHOSTS client that would prevent full automation to run the GHOSTS client on a windows system after it has been bootstrapped automatically?  

I have a AWS AMI (Windows Server 2022) I'm trying to automatically bootstrap with terraform and powershell so that it can run GHOSTS.  I have the oddest issue.  ghosts.exe does not look to be running correctly when the zip file is automatically extracted using terraform/powershell automation.  When I manually extract the zip file, ghosts.exe runs correctly.  By "run correctly", all applications launch (browser, office applications) from the default timeline.json as expected.

Steps to Duplicate this:
1.
When powershell script automatically runs through terraform user-data and extracts the GHOSTS zip file like this:
```
Expand-Archive -LiteralPath .\ghosts-client-x64-v8.0.0.zip
```
2.  
I then manually CD into the directory and run ghosts, ```.\ghosts.exe```.

3.
Results:
ghosts will launch with no errors.  The ```logs\app.log``` doesn't show any errors.  But no applications are auto-running from default timeline.json.

4.  Now I delete the ghosts directory that was extracted.
5.  Open up a new powershell session.  
6.  Extract the zip file like this by manually typing into powershell console:
```
Expand-Archive -LiteralPath .\ghosts-client-x64-v8.0.0.zip
```
7. Cd into directory and launch ghosts.exe.  Now applications are running automatically from ```timeline.json``` with expected results of launching office and browsers in default timeline.json.

The only difference between the two test cases is that I, as a human user, manually ran the zip archive extraction versus it running from terraform user-data with ec2 agent.  The powershell cmdlet was the same.  

Is there anything about GHOSTS and the Zip file that you know would be a factor here?  I've tried debugging this for days to figure out why the zip file extraction is different and not working when done through an automated configuration management tool like terraform + user-data + powershell.  Is there anything else I can share here or do to debug Ghosts further on why it isn't launching applications from timeline.json?

Thanks for any help here.

**Comment by sei-dupdyke** [comment]
Sorry for the delay, what did you find out here sir?
