### ISSUE TITLE
Network share based email content

### ISSUE THREAD

**Issue by drench79** [cmu-sei/GHOSTS#37]
It would be useful if within the Gh0sts client I were able to configure a network share location for email content to be used within the client application. So instead of a specific file in a specific location in relation to the install path I would like to be able to specify a path where the email content would reside.

**Comment by sei-dupdyke** [comment]
For v4 (just released), I added a new client config section:

```
"Content": {
    "EmailContent": "",
    "EmailReply": "",
    "EmailDomain": "",
    "EmailOutside": "",
    "FileNames": "",
    "Dictionary": ""
  },
```

which enables overriding the default content locations, so that if you want to use `//some_server/directory/file.csv` and share 1 file among clients, you can now do so. Thanks @drench79!
