### ISSUE TITLE
Timeline length

### ISSUE THREAD

**Issue by RANDW0LF** [cmu-sei/GHOSTS#38]
Is there a limit to the number of Handlers the timeline.json file can run.
I had 10 and it wouldn't run, I removed 3 and it worked fine.
Great tool btw, thanks in advance.

**Comment by sei-dupdyke** [comment]
Not that we're aware of - do you mind sending me the full 10 handler timeline, and I can do some testing? Thanks in advance and thanks for using GHOSTS!

**Comment by RANDW0LF** [comment]
Hi Dustin

Thankyou for your email.

Please close this off, it appears I may have had a syntax error when copy
and pasting entries in the timeline.
Apologies.

Regards
Randall

**Comment by sei-dupdyke** [comment]
Hello sir, if you don't mind, I'm going to keep it open and add a better error message for when this happens. JSON is notorious for syntax errors (I do it all the time) and I think I can easily fix this in the next dev cycle. Thanks for the update and for using the framework.

**Comment by sei-dupdyke** [comment]
For v4 (just released), I added specific error messages in the client console and logs for malformed json timelines. This should make it easier to track down these types of issues in the future. Thanks for helping to identify the issue and eventual fix, @RANDW0LF!
