### ISSUE TITLE
Win10 client doesnt connect to Server API

### ISSUE THREAD

**Issue by jela962** [cmu-sei/GHOSTS#39]
Hi everyone, hope the question is appropriate:

I have been trying for weeks to connect my Win10 client to server API, which is on Kali (which is on VMWare). Server is running up on :5000, i can access it in browser, Grafana is also running up on :3000, and I have createad postgre database and imported .json default dashboard. Also, ghosts is running on Win10 perfectly. 

The problem occurs when I try to connect client to server through application.json file (which is mentioned in documentation). I tried forwarding the server url in IdUrl variable, but it doesn't work. I also tried switching to bridged mode, and then forwarding the IP address/api/clientId, but it also doesn't work. I think I tried everything I could.

Does anyone know how to connect them? Many thanks in advance!

**Comment by sei-dupdyke** [comment]
Hi, thanks for using, sorry client check in has not gone smoothly. Let's troubleshoot in this order:

1. On the ghosts client machine, can you open a browser and get to http|s://<server_host>:<port>/api/home ? Does it render a snippet about server time, number of machines checked in, etc?

2. If you can successfully render the page from (1), double check your config/application.json - there are several entries for the above host/port that you must update to match:

```
        "IdUrl": "http://localhost/api/clientid",
ClientResults
        "PostUrl": "http://localhost/api/clientresults",
ClientUpdates
        "PostUrl": "http://localhost/api/clientupdates",
Survey
        "PostUrl": "http://localhost/api/clientsurvey"
```

3. If everything in config from (2) looks correct as well, run the kill-ghosts.bat script to stop all processes. Now look on the client to see if you have an /instance folder where ghosts is installed and delete that. Now restart ghosts.

4. If that still does not fix it, can you send me your logs/app.log file so we can debug further?

Thanks

**Comment by jela962** [comment]
Thank you for your answer!

I tried to render the snippet about server from step (1), and it couldn't load localhost:5000/api/home on client side. On server side, everything is fine.

Just to mention that I am trying to setup the client on my Windows 10, which is my origin host machine, and the server is on VMWare's instance, on Kali.

**Comment by sei-dupdyke** [comment]
Ok, we can fix that easily I think:

1. Go to kali and fire up a console window. Type `ip a` and take note of your public ip address
2. Open your web browser on that kali instance and hit http://<that ip address>:5000/api/home — do you see the initial stats page rendered?
3. on the client machine open a browser and try that same address — does it render
4. If so, on your client machine, replace localhost in those lines mentioned previously with <that ip address>:5000 and leave the rest as is...

LMK how it goes please.

**Comment by jela962** [comment]
I tried accessing http://:5000/api/home but it only displays me web results, it behaves like I did the standard google search, instead of hitting directly the server's URL.

Same on kali (server), same on Windows10 (client). I tried on Opera and Firefox at client's side. 

Also, I can access via localhost:5000/api/home on kali, but not on Windows. Network settings on VMWare is in bridged mode, so they should be definitely in the same subnet. Could be any problem with libraries, drivers, etc. ?

**Comment by avershave** [comment]
I think he meant to access the ip of the machine that's currently running the API.
So you would go to http://<public-ip-of-runningAPI>:5000/api/home

**Comment by sei-dupdyke** [comment]
Yep, get that public ip from the command run in step (1).

**Comment by jela962** [comment]
First of all, many thanks to all of you who are trying to resolve this problem, especially Dustin.

Sorry, maybe I was looking at the wrong ip address. Anyway, I tried with eth0 ip, with :5000 (<eth0 ip>:5000/api/home), and it can render the web page on client side, finally. 

After that, I tried step (3) previously mentioned (running kill.ghosts script, restarting the app), but no results, still 0 machines connected on server's webpage, and of course on Grafana's dashboard.

**Comment by sei-dupdyke** [comment]
Sorry for the delay.

Would you do me two favors please:

(1) On the client, look in logs/app.log and see if there are any glaring errors, if not, can you post here?
(2) Post your client config here

Thanks!

**Comment by jela962** [comment]
No problem.

(1) I found these repeating issues in logs/app.log file:
            Parameter name: value
   at System.Net.WebHeaderCollection.CheckBadChars(String name, Boolean isHeaderValue)
   at System.Net.WebHeaderCollection.Add(String name, String value)
   at Ghosts.Client.Infrastructure.WebClientBuilder.BuildEx(ResultMachine machine, Boolean hasId) in 
            Z:\Projects\ghosts\**Ghosts.Client\Infrastructure\WebClientHeaders.cs:line 39**
   at Ghosts.**Client.Comms.Updates.GetServerUpdates() in Z:\Projects\ghosts\Ghosts.Client\Comms\Updates.cs:line 60**
2020/09/23 19:32:50.577|Ghosts.Client.Comms.CheckId.get_Id|config file could not be opened
2020/09/23 19:32:50.831|Ghosts.Client.Comms.Updates.GetServerUpdates|Problem polling for new configuration
2020/09/23 19:32:50.954|Ghosts.Client.Comms.Updates.GetServerUpdates|System.ArgumentException: Specified value has invalid Control characters.

(2)```
"IdEnabled": true,
    "IdUrl": "http://192.168.8.118:5000/api/clientid",
    "IdFormat": "guestlocal",
    "IdFormatKey": "guestinfo.id",
    "IdFormatValue": "$formatkeyvalue$-$machinename$",
    "VMWareToolsLocation": "C:\\progra~1\\VMware\\VMware Tools\\vmtoolsd.exe",
    "ClientResults": {
        "IsEnabled": true,
        "IsSecure": false,
        "PostUrl": "http://192.168.8.118:5000/api/clientresults",
        "CycleSleep": 90
    },
    "ClientUpdates": {
        "IsEnabled": true,
        "PostUrl": "http://192.168.8.118:5000/api/clientupdates",
        "CycleSleep": 90
    },
    "Survey": {
        "IsEnabled": true,
        "IsSecure": false,
        "Frequency": "once",
        "CycleSleepMinutes": 5,
        "OutputFormat": "indent",
        "PostUrl": "http://192.168.8.118:5000/api/clientsurvey"
```

The rest of the configuration is same as default.

**Comment by sei-dupdyke** [comment]
Looking at these errors 1-by-1:

> Parameter name: value at System.Net.WebHeaderCollection.CheckBadChars(String name, Boolean isHeaderValue)
at System.Net.WebHeaderCollection.Add(String name, String value)
at Ghosts.Client.Infrastructure.WebClientBuilder.BuildEx(ResultMachine machine, Boolean hasId) in
Z:\Projects\ghosts\Ghosts**.Client\Infrastructure\WebClientHeaders.cs:line 39**
at Ghosts.Client.Comms.Updates.GetServerUpdates() in Z:\Projects\ghosts\Ghosts.Client\Comms\Updates.cs:line 60

line 39 gets the current username that ghosts is running as. What is the user that you are running this under? Anything special about that account?

> 2020/09/23 19:32:50.577|Ghosts.Client.Comms.CheckId.get_Id|config file could not be opened
2020/09/23 19:32:50.831|Ghosts.Client.Comms.Updates.GetServerUpdates|Problem polling for new configuration
2020/09/23 19:32:50.954|Ghosts.Client.Comms.Updates.GetServerUpdates|System.ArgumentException: Specified value has invalid Control characters.

How are you launching the exe? Sometimes I see issues with launching the exe from a tree ala 

`RUN c:\exercise\ghosts\ghosts.exe` 

rather than 

```
CD c:\exercise\ghosts 
RUN ghosts.exe
```

I had thought I had fixed this though, so I am not sure that is the issue here, but not being able to load the config is going to cause everything to fail that follows.

Thanks for being patient.

**Comment by jela962** [comment]
You were right about something speacial about the username, that was the problem all the time! My local account and username had "special characters", "š" and "ć", so that was causing the problem. I renamed it, and it works perfectly. Anyone who has same problem, double check your host username.

Once again, thank you so much for your help and patience, it is all fine now.

**Comment by sei-dupdyke** [comment]
I am going to reopen this so that in the next dev cycle we can catch these sorts of cases in code.

Thanks @jela962 for helping to get to the bottom of things.

**Comment by sei-dupdyke** [comment]
In v4 (just released), I added a config value to enable the base64 encoding of the machine username to mitigate these special cases.

"EncodeHeaders": true,

Will encode the username value that the client picks up. The server will automatically decode these when it detects a base64 encoded string.

Thanks @jela962 for helping find this issue and ultimately put it to rest!
