### ISSUE TITLE
instalation got stuck - using command docker-compose up -d 

### ISSUE THREAD

**Issue by desalva** [cmu-sei/GHOSTS#40]
Hi ,

i am trying to install by following the instruction on https://github.com/cmu-sei/GHOSTS/wiki/Installation-from-distribution-binaries

I got stuck and got error message :
Starting ghosts-postgres ... error

ERROR: for ghosts-postgres  Cannot start service postgres: error while creating mount source path '/Users/dustin/data/ghosts/db_data': mkdir /Users: read-only file system

ERROR: for postgres  Cannot start service postgres: error while creating mount source path '/Users/dustin/data/ghosts/db_data': mkdir /Users: read-only file system

I am using Vbox Ubuntu Server 20.4. I have tried to look for the answer in the internet by cannot find it.

Could you help me to solve the problem?

thanks

**Comment by sei-dupdyke** [comment]
Hi, this should be an easy fix.

In the docker-compose.yml file, change the volume path that maps the container storage to your local host machine

1. The volume lines that start with `/Users/dustin/data` — change this to your own user or other directory that exists on your host box that docker has permission to read and write from. It can be any directory, just as long docker can read and write from it. So, for example on line 17 (assuming your file looks like this https://github.com/cmu-sei/GHOSTS/blob/master/src/Ghosts.Api/docker-compose.yml), change:
      - /Users/dustin/data/ghosts/db_data:/var/lib/postgresql/data
to something like
      - /Users/your_username/data/ghosts/db_data:/var/lib/postgresql/data


2. run `docker-compose down` to reset any other assets that were stood up

3. run `docker-compose up -d` and you should be good to go

**Comment by desalva** [comment]
I have changed the yml file as suggested and it works.

thanks
