### ISSUE TITLE
Ghosts UI issue

### ISSUE THREAD

**Issue by Tequalequal** [cmu-sei/GHOSTS#418]
Hello!

There was already an issue post (#403) and I have the exact same problem and I was wondering is there any fix for it since it was just closed as completed without any comments.

**Comment by sei-dupdyke** [comment]
Oh, sorry, the issue there was that an API update was needed to add/wireup some endpoints. Do you have the latest version of the API?

**Comment by redwiz666** [comment]
I'm having similar issue using the current Images, 
Checked on docker hub and am using the latest images for both ghosts-ui and ghosts. 

Getting the 404 error when trying to push any timelines to clients.

**Comment by sei-dupdyke** [comment]
The endpoints were not quite aligned correctly, I fixed this in the api (8.2.3) and the ui (0.0.4) images - pull these versions or latest. Sorry about that.
