### ISSUE TITLE
compose-api.yml file

### ISSUE THREAD

**Issue by fhbermudez** [cmu-sei/GHOSTS#42]
I looked at the files I downloaded and was not able to find the "compose-api.yml".
Attempting to follow the instruction for the Docker-Based Setup.
Would you provide assistance on how to proceed?

**Comment by sei-dupdyke** [comment]
Hi, sorry for delay, I believe the file you need is [here](https://github.com/cmu-sei/GHOSTS/blob/master/src/Ghosts.Api/docker-compose.yml).

Which page did you see the reference for compose-api.yml - I will fix. Sorry about the confusion.

**Comment by fhbermudez** [comment]
Dustin,

Here is the link to the page:
https://github.com/cmu-sei/ghosts/wiki/Installing-the-Server-API

By the way, what type of server do you recommend for the server, Ubuntu,
Centos, or Mac?

Ran into this code and I am interested in running it in our cyber lab.

Thanks
Fred


FEDERICO H BERMÚDEZ

G 757-828-5623
W 757-203-4023
fhbermudez@gmail.com
fbermudez@tcc.edu
federico.h.bermudez.civ@mail.mil

**Comment by sei-dupdyke** [comment]
We strongly recommend docker install for ease of setup - [details are here](https://github.com/cmu-sei/ghosts/wiki/Installation-from-distribution-binaries)

If you want to continue to go down the standalone server install, we typically use centos here, but I know others have used ubuntu based on their preference.

I will update that page with correct links to files. Thanks for finding them.
