### ISSUE TITLE
Client RDP Handler COM Error

### ISSUE THREAD

**Issue by sei-dupdyke** [cmu-sei/GHOSTS#429]
COM error:

2024/10/07 
 9:22:44.905|Error|Ghosts.Client.Handlers.Rdp..ctor|System.Runtime.InteropServices.COMException: Retrieving the COM class factory for component with CLSID {1A671297-FA74-4422-80FA-6C5D8CE4DE04} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
 
Handler json:
```{
  "Id": "aafc0b4b-f33b-4f73-a60a-ae31cd873407",
  "Status": "Run",
  "TimeLineHandlers": [
    {
      "HandlerType": "Rdp",
      "HandlerArgs": {
        "CredentialsFile": "%homedrive%%homepath%\\Documents\\Credential.json",
        "mouse-sleep-time": 10000,
        "execution-time": 60000,
        "execution-probability": 100,
        "delay-jitter": 50
      },
      "Initial": "",
      "UtcTimeOn": "00:00:00",
      "UtcTimeOff": "24:00:00",
      "Loop": "False",
      "TimeLineEvents": [
        {
          "Command": "random",
          "CommandArgs": [
            "192.168.1.10|executive_cred",
            "192.168.1.12|executive_cred"
          ],
          "DelayAfter": 1000,
          "DelayBefore": 10000
        }
      ]
    }
  ]
}```
 

Credential.json? 
{
  "credentials": {
    "executive_cred": {
      "username": "administrator",
      "password": "tartans@1",
      "domain": "FIN"
    }
  }
}
 
Any direction on where to go from here would be greatly appreciated.

**Comment by sei-dupdyke** [comment]
@rbreesems - any ideas sir?

**Comment by rbreesems** [comment]
One problem is that the password in the credential file is supposed to be base64 encoded, so a plaintext password like that will not work. 

But as to the `Class not registered` problem - I don't know what is causing that.

**Comment by rbreesems** [comment]
To register the autoit DLL. To manually register a DLL file, you can use the Command Prompt as an administrator and enter the command regsvr32 <path to DLL file>: 
Open the Windows Search bar and search for cmd 
Right-click on cmd.exe and select Run as administrator 
Type the command regsvr32 <path to DLL file> and press Enter 
You can download the AutoIt package and other scripting tools from autoitscript.com. The AutoIt installer creates a directory structure, usually in \Program Files\AutoIt3, and Start Menu shortcuts

**Comment by rbreesems** [comment]
In the Ansible code that installs Ghosts, we register AutoIt with this task:

```
- name: Register autoit dll
  ansible.windows.win_command: "regsvr32.exe /S {{ item }}"
  args:
    chdir: C:\ghosts
  loop:
    - AutoItX3.dll
    - AutoItX3_x64.dll
  tags: setup

**Comment by sei-dupdyke** [comment]
Fixed with above, thanks @rbreesems!
