### ISSUE TITLE
Adding Data Source to Grafana

### ISSUE THREAD

**Issue by NsinR8** [cmu-sei/GHOSTS#43]
![image](https://user-images.githubusercontent.com/19197875/97607366-de6c3680-19de-11eb-8658-17df4b762818.png)

Cannot successfully add data source to Grafana. 

Error: dial tcp 127.0.0.1:5432:getsockopt: connection refused

**Comment by sei-dupdyke** [comment]
If you are using docker containers, you'll need to get out to the other container (127.0.0.1 in the container stays in the container).

Try `ghosts-postgres:5432` instead please, and LMK if that does not work. Thanks!

**Comment by NsinR8** [comment]
![image](https://user-images.githubusercontent.com/19197875/97618171-b7b4fc80-19ec-11eb-87b3-5c1b82eef7c6.png)

That makes sense. Well of course it does, now that I think of it. Success!

**Comment by sei-dupdyke** [comment]
Awesome!

This same issue still gets me too. Glad you got it working, let me know if I can help with anything else that crops up. Thanks for using!
