### ISSUE TITLE
Login and User Creation Errors in ChatClient (Extra `.` Added to Usernames)

### ISSUE THREAD

**Issue by dh4340** [cmu-sei/GHOSTS#442]
#### Description

I'm encountering several issues with the `ChatClient` in the `GHOSTS` API. The application is failing to log in users and create new users, resulting in a series of errors, including the addition of an extra `.` to the end of usernames. The details are outlined below.

#### Logs

```
ghosts-api       | 2024-10-15 11:44:39.1850|WARN|ghosts.api.Infrastructure.Animations.AnimationDefinitions.Chat.ChatClient|Could not login janet., scotty@1 with: System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
ghosts-api       | 2024-10-15 11:44:39.1850|TRACE|ghosts.api.Infrastructure.Animations.AnimationDefinitions.Chat.ChatClient|Using create user url: http://mattermost:8065api/v4/users
ghosts-api       | 2024-10-15 11:44:39.1850|ERROR|ghosts.api.Infrastructure.Animations.AnimationDefinitions.Chat.ChatClient|Create user failed System.UriFormatException: Invalid URI: Invalid port specified.
ghosts-api       | 2024-10-15 11:44:39.1850|WARN|ghosts.api.Infrastructure.Animations.AnimationDefinitions.Chat.ChatClient|Could not login lilly., scotty@1 with: System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
ghosts-api       | 2024-10-15 11:44:39.2012|ERROR|ghosts.api.Infrastructure.Animations.AnimationDefinitions.Chat.ChatClient|Cannot login admin@scotty.com:scotty@1 with error The operation was canceled.
```

#### Error Details

1. **Unauthorized Access (401)**: 
   - Users `janet.` and `lilly.` are unable to log in, resulting in unauthorized errors. Notice that an extra `.` has been appended to the usernames.
   
2. **Invalid URI Format**: 
   - The create user URL is malformed: `http://mattermost:8065api/v4/users` (missing a `/` before `api`). Fixed in my latest pull request.

3. **Operation Canceled**: 
   - Attempts to log in the configured admin account `admin@scotty.com` are canceled, leading to an inability to authenticate.

4. **Extra `.` in Usernames**: 
   - When logging in, usernames like `janet.` and `lilly.` have an extra `.` at the end, which is not expected. This may be causing the authentication issues.

#### Steps to Reproduce

1. Attempt to log in with various usernames (e.g., `janet`, `lilly`, and `admin@scotty.com`).
2. Monitor the logs for unauthorized errors and the incorrect username format with the extra `.`.
3. Attempt to create a new user and inspect the constructed URL for errors.

#### Expected Behavior

- Users should log in without unauthorized errors.
- Usernames should not have an extra `.` appended at the end.
- The application should construct valid URLs for user creation.

#### Additional Information

- Ensure that the Mattermost server is correctly configured to accept login requests and that the specified users exist.
- Review the logic in the `ChatClient` to ensure that the usernames are handled correctly and no extra characters (such as `.`) are appended.

**Comment by sei-dupdyke** [comment]
Hmm, in my testing, I don't get these results at all. I pulled your changes (thank you), and same - all of my users have first.last names. Do your NPCs before you turn on chat have full names?

**Comment by dh4340** [comment]
I've been using account names that only contain first names, which might be causing the issue. My usernames are just a single word, often not the user's actual name. Do your usernames have both first and second names? This difference could be contributing to the problem.

**Comment by dh4340** [comment]
I would suggest either a doc change to state system usernames need to be full names or a code change to allow for both. Happy to do the code change.

**Comment by sei-dupdyke** [comment]
I think the last commit should fix this. New container incoming...

**Comment by sei-dupdyke** [comment]
docker pull dustinupdyke/ghosts:8.2.6.100

[8.2.6.100](https://hub.docker.com/layers/dustinupdyke/ghosts/8.2.6.100/images/sha256-cbb1ab587c475d21c2ffa38f440eacd05bbb510580ddedb1e1a60743716a3e69?context=repo)

Let me know if you continue to see problems here. Thanks for working through these issues with me.

**Comment by dh4340** [comment]
No probs, I'm enjoying it. I want to try and help as much as I can. I'll pull the new container and have a try.

**Comment by dh4340** [comment]
Fixed but new errors, will post issue once i figure out if it's me or not.
