### ISSUE TITLE
Incorrect Email Format in Pandora Socializer Code

### ISSUE THREAD

**Issue by dh4340** [cmu-sei/GHOSTS#447]
The Pandora Socializer code is causing an error due to incorrect email formatting. It appears that the code expects a surname to be part of the username when constructing the email, which rarely happens in practice. This leads to invalid email addresses with two consecutive dots, such as `bob..mil@mail.mil`.

**Example of Problematic Email:**
```json
"Email": "bob..mil@mail.mil"
```

**Root Cause:**
The code that generates usernames and email addresses likely assumes a specific format, resulting in double dots in cases where the expected surname is not provided. This issue affects validation and processing of user information, particularly in cases where accurate email formatting is crucial.

**Potential Fix:**  
Correct the logic to ensure the email address adheres to proper formatting standards and avoid generating usernames with consecutive dots. Review how usernames are being constructed to account for scenarios where a surname might not be present.

**Related Components:**
- Pandora Socializer Code
- Email address generation logic

**Comment by sei-dupdyke** [comment]
Hmm, Socializer takes any one of an array of different username values, such as:

`new[] { "user", "usr", "u", "uid", "user_id", "u_id" }`

but not email. It does no generation of usernames or email addresses based on names — Pandora and Socializer were built to just take whatever you send them, valid or not, so the problem is likely not there.

This is probably a generation problem within the API as you were seeing in other areas. Give me a bit to look around.

**Comment by dh4340** [comment]
Admit this one I didn't look at the code as assumed same issue.

**Comment by sei-dupdyke** [comment]
Sending social media posts from the API generates a client form post like this:

```
request.AddParameter(userFormValue, agent.NpcProfile.Name.ToString());
request.AddParameter(messageFormValue, tweetText);
```

and Name.ToString() assumes first and last and only checks for middle — this is likely the problem.

I have to admit I did not test with single names. Are you simulating pop stars?

**Comment by sei-dupdyke** [comment]
`docker pull dustinupdyke/ghosts:8.2.6.196` thanks for reporting.

**Comment by dh4340** [comment]
Cheers for fixing, I'm just using linux for my testing so account names tend to be single words, so when you sync the NPC this issue takes place.

**Comment by sei-dupdyke** [comment]
Totally makes sense, always surprising when you don't account for these things, how deep they sometimes go.
