### ISSUE TITLE
Wiki docker-compose.yml hyperlink incorrect

### ISSUE THREAD

**Issue by AlexSchrichte** [cmu-sei/GHOSTS#45]
The installation page https://github.com/cmu-sei/GHOSTS/wiki/Installation-from-distribution-binaries

references a docker-compose.yml but the hyperlink refers to: 
https://github.com/cmu-sei/GHOSTS/blob/master/src/Ghosts.Api/Dockerfile

I think the intention may have been to refer to: 
https://github.com/cmu-sei/GHOSTS/blob/master/src/Ghosts.Api/docker-compose.yml

Is it possible to update the wiki to reflect this?

**Comment by sei-dupdyke** [comment]
Yep, thank you for finding this. I've updated the wiki page to point to the correct docker-compose file.
