### ISSUE TITLE
[Windows Bug] Windows Client RDP Handler Error

### ISSUE THREAD

**Issue by nblair2** [cmu-sei/GHOSTS#458]
Thank you for this useful tool. I have been able to install and successfully use many of the features, but whenver using an RDP handler, get an error:
`31/10/2024 8:07:30 AM|Error|Ghosts.Client.Handlers.Rdp..ctor|System.Runtime.InteropServices.COMException: Retrieving the COM class factory for component with CLSID {1A671297-FA74-4422-80FA-6C5D8CE4DE04} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).`

Some basic googling led me to believe that the COM component had to be registered, so I tried to run `regsvr32 C:\<path to ghosts>\System.Runtime.InteropServices.dll` but got an error:
![image](https://github.com/user-attachments/assets/a1ea7542-9a02-4770-837c-a28269a2d061)

I am using GHOSTS Client version 8.2 on a Windows 11 x64. Additional configuration information:
```bat
> .\ghosts.exe --version
             ('-. .-.               .-')    .-') _     .-')    
            ( OO )  /              ( OO ). (  OO) )   ( OO ).  
  ,----.    ,--. ,--. .-'),-----. (_)---\_)/     '._ (_)---\_) 
 '  .-./-') |  | |  |( OO'  .-.  '/    _ | |'--...__)/    _ |  
 |  |_( O- )|   .|  |/   |  | |  |\  :` `. '--.  .--'\  :` `.  
 |  | .--, \|       |\_) |  |\|  | '..`''.)   |  |    '..`''.) 
(|  | '. (_/|  .-.  |  \ |  | |  |.-._)   \   |  |   .-._)   \ 
 |  '--'  | |  | |  |   `'  '-'  '\       /   |  |   \       / 
  `------'  `--' `--'     `-----'  `-----'    `--'    `-----'  


ghosts:8.0.0.0 [8.2.2.0]
mscorlib: 4.0.0.0
NLog: 5.0.0.0
Ghosts.Domain: 8.2.0.0
Quartz: 3.8.1.0
CommandLine: 2.9.1.0
System: 4.0.0.0
System.Management.Automation: 3.0.0.0
Newtonsoft.Json: 13.0.0.0
System.Management: 4.0.0.0
Microsoft.VisualBasic: 10.0.0.0
FileHelpers: 3.5.2.0
System.Core: 4.0.0.0
Renci.SshNet: 2024.0.0.0
Microsoft.Management.Infrastructure: 1.0.0.0
WebDriver: 4.0.0.0
Microsoft.Office.Interop.Outlook: 15.0.0.0
System.Windows.Forms: 4.0.0.0
System.Drawing: 4.0.0.0
ExcelApi: 1.9.5.0
PowerPointApi: 1.9.5.0
WordApi: 1.9.5.0
Microsoft.AspNetCore.SignalR.Client.Core: 8.0.4.0
Microsoft.AspNetCore.Http.Connections.Client: 8.0.4.0
Microsoft.CSharp: 4.0.0.0
System.DirectoryServices.AccountManagement: 4.0.0.0
System.Runtime.InteropServices.RuntimeInformation: 4.0.2.0
System.Web: 4.0.0.0
NetOffice: 1.9.5.0
OfficeApi: 1.9.5.0
Microsoft.AspNetCore.SignalR.Client: 8.0.4.0

> reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP"
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\CDF
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0
```

Any help would be appreciated, thank you!

**Comment by lautriv** [comment]
FYI @nblair2 - I ran into a similar situation and was able to resolve it by manually running the `regsvr32.exe` commands referenced in https://github.com/cmu-sei/GHOSTS/issues/429#issuecomment-2403269945

**Comment by nblair2** [comment]
@lautriv this appears to have fixed the error. Thank you.

I will put in a PR to update documentation (any pointers on where this would be preferred are welcome).

**Comment by nblair2** [comment]
#466 addresses this
