### ISSUE TITLE
Open a file from network share and edit

### ISSUE THREAD

**Issue by RANDW0LF** [cmu-sei/GHOSTS#47]
I am using the following timeline to open a file, is this the best way to do it?
Also is there a way to then add contect to the file like the create function does?

```
{
    "Status": "Run",
    "TimeLineHandlers": [
        {
            "HandlerType": "Command",
            "Initial": "",
            "UtcTimeOn": "00:00:00",
            "UtcTimeOff": "24:00:00",
            "Loop": "False",
            "TimeLineEvents": [
                {
                    "Command": "explorer %homedrive%%homepath%\\Documents\\abacus.xlsx",
                    "CommandArgs": ["exit"],
                    "DelayAfter": 1000,
                    "DelayBefore": 0
                }
            ]
        }
    ]
}
```

**Comment by sei-dupdyke** [comment]
Hmm sorry, I hadn't thought of opening a particular existing file and editing it in that way. 

Rather, if you look a the [timeline sample for Word here](https://github.com/cmu-sei/GHOSTS/blob/master/src/Ghosts.Client/Sample%20Timelines/Word.json), you can only specify the output.

I think I can add this pretty easily though across all the office products, and provide some better methods for adding custom content regardless of how the file was/gets created. 

@RANDW0LF — Do you have a pressing need for this or can I prioritize as normal?

**Comment by RANDW0LF** [comment]
Sorry for the late reply.

Rather than creating a file, I was specifically after the best way of
opening a pre-existing file.

Not urgent, as the above code seems to at least open a file from a network
share or any location for that matter, but the file does quickly close
which I am not sure why.
