### ISSUE TITLE
Missing ghosts-id header

### ISSUE THREAD

**Issue by clenk** [cmu-sei/GHOSTS#470]
My server logs keep reporting 
> ghosts.api.Controllers.Api.ClientIdController.Index|Request missing ghosts-id header
ghosts.api.Controllers.Api.ClientUpdatesController.Index|Request by 

If I understand correctly, this code in `ClientIdController.Index()` is hit when the client reaches out to get their Ghosts ID.

https://github.com/cmu-sei/GHOSTS/blob/e51e4c40ddae5863131f5e2f1b7bea122ebc701f/src/Ghosts.Api/Controllers/Api/ClientIdController.cs#L34-L38

But the client won't have an ID yet, so won't it always hit this, return the `Missing ghosts-id header` error, and never give the client an ID?

When I commented out the above lines (and changed a couple log lines below that reference the id, the client was able to get an ID and continue.

**Comment by clenk** [comment]
No, on a freshly-compiled client it does not.

**Comment by sei-dupdyke** [comment]
Check the logs/application.log file - are there errors in here?

Thinking the client cannot connect to the api for some reason...

**Comment by sei-dupdyke** [comment]
#473

**Comment by clenk** [comment]
Much appreciated!

**Comment by sei-dupdyke** [comment]
Fixed and built a new container — please do `docker pull dustinupdyke/ghosts:8.2.6.200`
