### ISSUE TITLE
File Permissions in Grafana Container

### ISSUE THREAD

**Issue by jonebeabout** [cmu-sei/GHOSTS#48]
Following steps from docker-compose install leads to a continuous reboot of the grafana container. A `docker logs` command on the container led me to a file permission issue within the container with permission denied errors to anything located in `/var/lib` .  I edited the docker-compose.yml file with this line to log in as root instead of the default user on boot:
`user: root`

Probably not ideal in the long run, but maybe something you want to take a look at.

**Comment by sei-dupdyke** [comment]
Hi! Good point. On some systems where I see this a chown of the grafana volume listed in the docker-compose file with the docker user fixes it as well:

```
  - /Users/dustin/data/ghosts/g_data:/var/lib/grafana
```

I'll leave this issue open so as to look for a better solution in the next release. Thanks for posting this up.

**Comment by sei-dupdyke** [comment]
I can't figure out an automated way to deal with this insufficient permissions issue, and so I updated the wiki to caution you may need to mod the host volume permissions.
