### ISSUE TITLE
emails-outside.json

### ISSUE THREAD

**Issue by RANDW0LF** [cmu-sei/GHOSTS#55]
My ghosts instance doesnt seem to be using the "emails-outside.json"

Is anyone able to assist and advise on how this is called upon. I can't work out if it is in application.json or elsewhere.

**Comment by sei-dupdyke** [comment]
Hi - Sorry, but this is a bug. I will add to the high-priority list. For now, you could simply add those emails to the inside list.


(To your other point, you can specify a different file for email lists in application.json, under ContentSettings — but the default is indeed `emails-outside.json`.)

**Comment by sei-dupdyke** [comment]
This is working with checkin `e939fc...`, will be available in next binary release.
