### ISSUE TITLE
Z:\Projects\ghosts\src\Ghosts.Client references in the app log file

### ISSUE THREAD

**Issue by RANDW0LF** [cmu-sei/GHOSTS#58]
I have just trying to understand what the Z:\Projects\ghosts\src\Ghosts.Client references in the app log file are, when using the v4.0 simple windows zip.
I just have ghosts copied into C:\ therefore all the Ghosts.Client\......cs files are not there.

**Comment by sei-dupdyke** [comment]
That's just my local development env path for the original source code, not the install path on your box. When we track down bugs, it's helpful for knowing class/method origin.

**Comment by RANDW0LF** [comment]
Thankyou
