### ISSUE TITLE
Remotely Starting Ghosts

### ISSUE THREAD

**Issue by RANDW0LF** [cmu-sei/GHOSTS#59]
I have some scripts that use psexec to remotely kill ghosts from a domain server, but when trying to start ghosts remotely I have an issue with ChromeDriver.
It errors with:
```
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
```
I have tried a few methods using psexec as well as Invoke-Command or Enter-PSSession but get the same results or other issues. 
eg. psexec \\workstation1 C:\Ghosts\ghosts.exe
or Invoke-Command -ComputerName CAN-B1-WS-10 -scriptblock {& 'c:\Ghosts\ghosts.exe}

I am looking at more options to attempt to force a task to run locally, but I thought I would check in to see if you had any ideas. I think there is a while to have chromedriver  --whitlisted-ips="" but I think I would need to compile it that way?

**Comment by sei-dupdyke** [comment]
Hi, we were discussing internally, I don't think we have used psexec to run GHOSTS here. We want it to run as the user, so we typically start it with a powershell startup or login script.

I'm still digging, standby please...

**Comment by sei-dupdyke** [comment]
We use a simple function 
```powershell
function Start-Ghosts() {
	Set-Location -Path c:\step\ghosts
	Start-Process ghosts.exe -WindowStyle Hidden
}
```
and then call that in the login script.

**Comment by RANDW0LF** [comment]
Yes I use it at login, but this is to conduct stop/start function remotely on a number of workstations.
Thanks for the response I'll look into how I could implement function remotely, perhaps as a script on the local box and then call that script remotely. Just need to trick the chromedriver.

**Comment by nunoguerreiro** [comment]
@RANDW0LF  @sei-dupdyke  can you provide a sample here ?

I'm not getting any info in grafana timeline breakdown and not sure how to replicate this error. 
I copy all the client files in a logonscript everytime a specific user autologon but timeline is always empty.

I do not have the instance folder in the source (that I use to copy to each client machine).

Can you advise ?

![image](https://user-images.githubusercontent.com/1771943/110953777-2c1b8700-8361-11eb-983a-d14c5eca4b83.png)

**Comment by sei-dupdyke** [comment]
In the upper right corner of the grafana dashboard is the selected timespan that it is querying, here:

![Screen Shot 2021-03-12 at 10 41 00 AM](https://user-images.githubusercontent.com/43444464/110962885-754ae700-831f-11eb-8285-669e84e87d9a.png)

Expand it out until you see the data, then you can zoom in. Sometimes there is a mismatch in timestamps and grafana doesn't show any data right away.

**Comment by nunoguerreiro** [comment]
Think the problem in on the server side. See ticket https://github.com/cmu-sei/GHOSTS/issues/61
