### ISSUE TITLE
Compiling issues with Redemption

### ISSUE THREAD

**Issue by johnagr** [cmu-sei/GHOSTS#6]
Hi, I am trying to compile the Windows client with visual studio 2019, but I received several errors related to RedemptionLoader.cs and outlook.cs.

 I installed the Developer version from dimastr.com

[errors.xlsx](https://github.com/cmu-sei/GHOSTS/files/3360563/errors.xlsx)

Thanks.

John

**Comment by avershave** [comment]
you have to add the redemption.dll and redemption32.dll as a com in visual studio.

**Comment by johnagr** [comment]
It's working great!.

Thanks.
