### ISSUE TITLE
GHOSTS API not differentiating between multiple VMs originating from the same *.ova image

### ISSUE THREAD

**Issue by GeorgiNikolovRMA** [cmu-sei/GHOSTS#62]
Hello,

i have been experimenting with the GHOSTS framework for some time now and I wanted to do a big scale test of it by connecting multiple Windows Clients to the GHOSTS server. I have a Windows10 *.ova image that i used to instantiate 5 VMs in VirtualBox, with each VM having a different IP and computer name. 

I connected each Windows Client to the GHOSTS Server Api via the application.json file and they all work, but with one major flaw: the 5 VMs are all considered as one and the same by the Server API and viewing the output in Grafana I only see 1 NPC active (the first machine that connected to the API). Looking into the postgresql db I also see only one table entry in the "machines" table, even when 5 VMs are running.

I would like to know if this is normal behavior. How does the GHOSTS Api differentiate between different Clients (does it look at the Windows Device ID for example?) and is there a way to have 5 VM clones run as clients and still be considered different clients by the GHOSTS server.

Thank you

**Comment by sei-dupdyke** [comment]
Hi! There are a couple of things to check:

1. The ID for a client is generated on first check-in and stored in `./instance/id.json` — if you run ghosts and then clone it, this ID gets copied and all the clients will report in as the same ID. This folder should not be copied.

2. On the API side, there are several ways to match machines ("how does the API distinguish one client from another?") — `fqdn`, `host` or `resolvedhost` or `name` (name is default, unless overridden in the appsettings.json file as one of the other values for `MatchMachinesBy`. So if you've left the API on the default settings, and you're running the same machine name on several enclaves, they'll report in as the same client.

LMK if that makes sense and what you find.

**Comment by GeorgiNikolovRMA** [comment]
Thank you for the fast response! 

I removed the `./instance/` folder from the ghosts client machines and it solved my issue. The different machines got assigned new ids and are regarded as different entities by the GHOSTS Api Server. 

I consider this issue closed as you completely answered my question :)
