### ISSUE TITLE
Skype for Business Handler

### ISSUE THREAD

**Issue by RANDW0LF** [cmu-sei/GHOSTS#64]
This is a bit beyond me, but a Skype for Business handler would be a neat addition. Most likely a lot of DEV time similar to Outlook I imagine.

**Comment by sei-dupdyke** [comment]
I'm not 100% sure, but the other consideration might be that it seems Skype is being killed off in lieu of Teams. Is there a better chat app we might wire up instead?

**Comment by RANDW0LF** [comment]
Agreed, Teams is not on the road map as a on-premise solution therefore a better chat app like openfire and spark perhaps. 
Just opening up the forum for it. 
Cheers
