### ISSUE TITLE
Problems with the Bash timeline

### ISSUE THREAD

**Issue by joliva114** [cmu-sei/GHOSTS#67]
Hi, first I'd like to say that this a really cool project, and managed to deploy it with 5 win7 NPCs, along with SPECTRE. I'd like to deploy also on Kali machines, I have managed to have Curl working but I'm struggling with bash timelines, and I can't find documentation on how to do it. Would you please share us a sample bash timeline?

**Comment by sei-dupdyke** [comment]
Thanks for trying it out! There is a [sample bash handler here](https://github.com/cmu-sei/GHOSTS/blob/master/src/Ghosts.Client/Sample%20Timelines/Command.json) - but if you want to do something specific drop me a note here or via email and I'll dig into it further.

**Comment by joliva114** [comment]
Thank you for you kind and quick response, it worked like a charm! I'm using this project to trigger XSOAR detections. I'm gonna make some scripts for IOC, I'll be happy to share with you when I finish them.

**Comment by sei-dupdyke** [comment]
Awesome, thank you!
