### ISSUE TITLE
Make email client click on links programmatically and randomly

### ISSUE THREAD

**Issue by dustinupdyke** [cmu-sei/GHOSTS#7]

**Comment by JackOfAllThings67** [comment]
where are you at on this one? what can i do to help?

**Comment by sei-dupdyke** [comment]
It's in the latest windows client build listed [here](https://github.com/cmu-sei/GHOSTS/wiki/Installation-from-distribution-binaries) - try it and let me know if you see any problems. Also welcome any improvements to how it gets used - thanks!
