### ISSUE TITLE
Issues with ghosts client config file and unsuccessfully starting the ghost client 

### ISSUE THREAD

**Issue by samuelgerard** [cmu-sei/GHOSTS#71]
Hello there, I'm trying to set up the ghosts for my network and I've run into an issue where I am unable to successfully launch the ghosts client on the client-side host of the ghosts setup.

***The Setup***:
Currently I am only running a test setup with two machines on the network, eventually I will setup all end host on the entire network to be ghosts clients with 1 machine that will be provisioning the ghost packets. The current test setup involves:
- Kali machine (the one that will be the ghosts client)
- Debian 10 machine (the API)

***Where I am at***:
So up to this point, I've completely set up everything from the docker containers containing the db, grafana, and API, setting up grafana on the debian 10 machine, and finally to where I'm at now to executing the ghosts client binary in my kali machine.

***The issue***:
I get the following error as i execute the command `dotnet ghosts.client.linux.dll`
`| ERROR | ghosts.client.linux.Comms.CheckId | config file could not be opened`

I'm unsure of what is causing this issue because I have not changed any of the file names in the entire linux ghost client directory of my kali machine. The only thing I have done is modify the applications.json file with the url of my API and it's endpoints.

The ghost client I am trying to set up is version 3.0.0.0

EDIT: Here is the entire output when I attempt to execute ghosts client

=================== Beginning of output ======================

         	('-. .-.           	.-')	.-') _ 	.-')    
        	( OO )  /          	( OO ). (  OO) )   ( OO ).  
  ,----.	,--. ,--. .-'),-----. (_)---\_)/ 	'._ (_)---\_)
 '  .-./-') |  | |  |( OO'  .-.  '/	_ | |'--...__)/	_ |  
 |  |_( O- )|   .|  |/   |  | |  |\  :` `. '--.  .--'\  :` `.  
 |  | .--, \|   	|\_) |  |\|  | '..`''.)   |  |	'..`''.)
(|  | '. (_/|  .-.  |  \ |  | |  |.-._)   \   |  |   .-._)   \
 |  '--'  | |  | |  |   `'  '-'  '\   	/   |  |   \   	/
  `------'  `--' `--' 	`-----'  `-----'	`--'	`-----'  
GHOSTS (ghosts.client.linux:3.0.0.0) running in production mode. Installed path: /root/ghost2/ghosts-client-linux-v3.0
2021-07-16 18:48:32.2338|ERROR|ghosts.client.linux.Comms.CheckId|config file could not be opened
Listener active on 10.0.100.10,fe80::a800:ff:fe28:ebb2%2,10.1.0.1,10.1.1.1,fe80::a800:ff:fe0d:de5d%3,fe80::a800:ff:fee6:a074%4 : 8443
Unhandled exception. Unhandled exception. System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.GetHostEntry(String hostNameOrAddress)
   at Ghosts.Domain.ResultMachine.GetLocalIPAddress() in /Users/dustin/Projects/ghosts/Ghosts.Domain/Messages/MesssagesForServer/ResultMachine.cs:line 99
   at Ghosts.Domain.ResultMachine..ctor() in /Users/dustin/Projects/ghosts/Ghosts.Domain/Messages/MesssagesForServer/ResultMachine.cs:line 19
   at ghosts.client.linux.Comms.Updates.GetServerUpdates() in /Users/dustin/Projects/ghosts/ghosts.client.linux/Comms/Updates.cs:line 48
   at ghosts.client.linux.Comms.Updates.<>c.<Run>b__1_0() in /Users/dustin/Projects/ghosts/ghosts.client.linux/Comms/Updates.cs:line 34
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.GetHostEntry(String hostNameOrAddress)
   at Ghosts.Domain.ResultMachine.GetLocalIPAddress() in /Users/dustin/Projects/ghosts/Ghosts.Domain/Messages/MesssagesForServer/ResultMachine.cs:line 99
   at Ghosts.Domain.ResultMachine..ctor() in /Users/dustin/Projects/ghosts/Ghosts.Domain/Messages/MesssagesForServer/ResultMachine.cs:line 19
   at ghosts.client.linux.Comms.Updates.PostClientResults() in /Users/dustin/Projects/ghosts/ghosts.client.linux/Comms/Updates.cs:line 157
   at ghosts.client.linux.Comms.Updates.<>c.<Run>b__1_1() in /Users/dustin/Projects/ghosts/ghosts.client.linux/Comms/Updates.cs:line 40
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

zsh: abort  	dotnet ghosts.client.linux.dll

=================== End of output ======================

**Comment by sei-dupdyke** [comment]
Hi, thanks for giving the project a look.

The application can't find its config files. This happens if you execute from another directory. Are you executing `dotnet ghosts.client.linux.dll` from the directory where it is located? If not you need to `cd /root/ghost2/ghosts-client-linux-v3.0` and then run the application. Sorry for the inconvenience.

**Comment by samuelgerard** [comment]
Thank you for the reply.

Yes, I'm executing the `ghosts.client.linux.dll` binary in it's exact directory where it is originally located when I unzipped the clients binarys `/root/ghosts2/ghosts-client-linux-v3.0`.  Does the client binarys potentially require an absolute directory path name? 

Here's an exact view of me attempting to execute the client binarys.

![image](https://drive.google.com/uc?export=view&id=1nTcbQPBW2a3GU_znBxRtbOwgyfO1Mh0z)


I tried again and redownloaded the linux client package and tried setting up the client binary in another separate directory called `/root/ghosts3/`, unfortunately I'm getting the exact same error again.

I'm going to try and run the 2.6 client as well, see if I get better result than with 3.0.0.0 version.

**Comment by sei-dupdyke** [comment]
Hmm, permissions? Does the user account have access to everything in the ghosts install directory? Maybe try a `chown`?

**Comment by samuelgerard** [comment]
I've actually already tried that previously, I thought it had to do with root permissions so I `chown`ed the directory while also providing root privileges. Same thing however, an issue of not being able to open the config file, I even tried to run the application directly as root and still no avail.

My attempt with running the 2.6 Linux Ghosts client didn't work out exactly either, the exact same issue of not being able to open the config file/directory.

I'll try running the ghosts client installation on a fresh kali machine and see how that goes.

**Comment by samuelgerard** [comment]
Update: running on a fresh machine doesn't work, however, I tried testing localhost on the ***Debian*** machine that is hosting the API docker containers. I did the same steps and installed ghost client on the debian machine and ran its configurations as localhost to the correct ports. 

It ended up working and I'm seeing activity on my grafana web page. This slightly confused me but I think I narrowed down the possibilities. I believe it has to do with potential privileges on the debian machine since the localhost ran ghosts client runs just fine. 

however, I'm still somewhat confused because both the machines are on the same private network and the kali machine can access the IP:port URL and display the grafana login and GHOSTS API, yet it can't seem to apply the proper configurations.

**Comment by sei-dupdyke** [comment]
Any of the client endpoints require a specialized set of header values that are used to track information about the requesting client such as their id, information about the host they run on, and so forth, so that 500 error is expected (and you can likely see more detail if you do a `docker log` command for the API container.

I know that there used to be issues with dotnetcore running on kali — I think it was not recommended — but that's been some time ago, and I need to look up if that still remains an issue. However, that typically is an issue with running dotnet, period, not specific parts of the code that fail in the manner that we are seeing here. Unless you really want to use kali, perhaps we can try another distribution (we have been using centos up until very recently, and will be switching to ubuntu, so those two have been tested very recently). In the meantime, I'll get a new kali box setup here and test today.

Sorry for all the hassle, I've not seen this particular error before. I should have some time to dig into it further today.

**Comment by sei-dupdyke** [comment]
Oh, have you verified that you have updated the `config/application.json` file with the correct URLs? The default values are likely not going to work on your network - look at idurl, posturl and the like and make sure they are routable back to your API server.

**Comment by samuelgerard** [comment]
Thank you as well for helping me through this.

Right now, I'm trying to get ***ghosts*** running on our cyber range asap. I've noticed  that a majority of the issues addressed with ghosts and the wiki installation guides are mostly meant towards installation on a windows OS. 

For now, I will spin up a windows 10 VM and run ghosts on that, then I will bridge it to the kali end host that users will interact with so that they can see things like ghost activity and wireshark packet information. 

I've kinda learned over the past couple days while tinkering with ghosts that it probably isn't really meant to run on kali haha, considering the debian client ghost test came out fine.

=======================

To go back to the issue at hand-

Here are screenshots below of the configuration of the clients `config/application.json` and screenshots of me verifying that API is working on debian server.

I've double-checked to make sure the configurations URL parameters were as they are expected to be.

***applications.json configuration***:
![image](https://drive.google.com/uc?export=view&id=1-wUlUdSOGrAoLbdnAZwjCCUYa8CpbGYz)


***Verifying that the API is working***:
![image](https://drive.google.com/uc?export=view&id=1Xir5axZZCnY43pSOlcBsYxu7YB5vGCbr)

**Comment by sei-dupdyke** [comment]
Sorry, but I'm stumped here. On my distros it works first time. Is the API image from the kali box to 10.0.100.237? If you can make that request in the browser, you should have no issues from ghosts - its just a web request under the hood.

**Comment by samuelgerard** [comment]
@sei-dupdyke 

Hello again, Sorry for leaving this issue up and not responding. We've switched production to a debian/windows 10 setup to operate ghost and ghost client for our end host. I've tried looking back at the problem and can't seem to figure out the problem myself, it's potentially a local system issue and I've trying to run around a find the issue 

I believe it's a local system issue because I reinstalled and reconfigured ghosts on my own personal home network and ghost linux client worked fine on my own spun up kali image; I was seeing content and data being generated and displayed on my grafana graph on my personal network. 

Due to the fact that, regardless that ghosts linux client isn't meant to really run on kali, I got the client to run just fine on my home system via kali. When I identified that, I didn't really bother to see why it's not working on the production network/system.

My last resort option would be to clone the entire ghosts code, create an absolute path to config repository, then compile the system. However, We've got a good setup going on production so I saw really no reason to spend extra time on that, since it's just a personal system based problem.

Maybe I'll go ahead and close this issue in a bit.

**Comment by sei-dupdyke** [comment]
No worries, I have been consumed with another project lately, but it looks like I will be able to get back to GHOSTS shortly. I will take a further look at Kali when I get a chance to do so. You can leave this open so that I am sure to look at it straight away. Sorry again for the troubles.

**Comment by samuelgerard** [comment]
No worries, thanks again for all the help possible, If i happen to get back to trying to resolve that issue and come across something. I will let you know.

**Comment by rquarry** [comment]
This isn't just a Kali problem. I've been getting the exact same errors with Ubuntu 20.04 hosts instantiated via Vagrant. Getting the API server running is a cinch, but I receive identical errors on the client as in the original post of this issue. I'll post more details if I can get some time to re-run the environment.
