### ISSUE TITLE
Application.json configuration to have clients send data to timeline endpoint

### ISSUE THREAD

**Issue by iknowjason** [cmu-sei/GHOSTS#76]
Hi,

GHOSTS looks to be a great framework.  Thanks Dustin for all of your work on this.  Question:  I'm trying to have the clients send their timeline data to the timeline endpoint.  The grafana dashboard doesn't show any data, and the sample application.json doesn't seem to include a direct endpoint for timeline.  I might not be looking in the right place or using the right application.json but I fail to see where a sample configuration is for this. 

In a prior issue #61, you indicated that the client endpoints total 5 and this includes "ClientTimeline".  Yet I only see 4 endpoints in the application.json provided.
Reference:

https://github.com/cmu-sei/GHOSTS/issues/61

Here is the client configuration application.json that we are using.  Can't find what the "ClientTimeline" endpoint configuration is supposed to look like:

https://github.com/cmu-sei/GHOSTS/wiki/Installing-The-Windows-Client

Here is a picture of our Grafana dashboards with client timelines showing blank.

![grafana](https://user-images.githubusercontent.com/4335973/135502412-3e1c8dfc-a4e2-4689-851e-333c2eaf7452.png)

**Comment by sei-dupdyke** [comment]
Hi, thank you for checking out the project.

You should see 5 endpoints on the API side that I was referring to in #61 - here is a screen of the swagger view of them:
![image](https://user-images.githubusercontent.com/43444464/135509666-f5e2ac11-2347-4d4d-b825-3b800b4fab25.png)

There really isn't any config for these that would keep your timelines from posting up to the API. Looking at your client logs/ clientupdates.log file look like? What size is it?

Are there any errors in logs/app.log relating to sending the updates?

**Comment by iknowjason** [comment]
Oh, this is helpful.  I was looking for something that was missing in application.json because we did have to customize this to get the clients talking properly to the API.  I assumed (mistakenly) that it was the same for ClientTimeline since I saw you mention 5 endpoints but only 4 were in application.json.  

I will check out the client logs/clientupdates.log to see if it gives some more information on the issue.

Thanks @sei-dupdyke

**Comment by sei-dupdyke** [comment]
No probem. The reason I ask about that file's size, is that sometimes it becomes unwieldy and the post up to the API times out and it fails. Check those logs first and lmk if there is still an issue.

**Comment by iknowjason** [comment]
Ok I checked the logs directory, looking in both "app" and "clientupdates".  They don't show any obvious errors.  clientupdates is 0 bytes and app is 2 KB doesn't show any obvious errors.  

Where else can I look to tell why the client is not POST'ing data to /api/clienttimeline

Yes I saw the Swagger API and as I was looking at it, that's why I posted here because I couldn't go any further.  It looks like from the swagger documentation you can use any client like curl to query the API and you should be able to pull from the clienttimeline similar to how the Grafana dashboards are supposed to render them.  For example, I do a GET query to get the machine IDs.....then I do a GET query to /timeline/{machine_id}.  Returns nothing.  Looks like the API endpoint is accessible but there is no data.  Thus my question back to the client and how do we tell the client to send to timeline or debug why they are not sending.

![Screen Shot 2021-09-30 at 2 17 25 PM](https://user-images.githubusercontent.com/4335973/135517151-cea0473c-6e7d-48ad-9850-59fa918ac923.png)
.

**Comment by sei-dupdyke** [comment]
Hmm... What version of the ghosts-api docker image are you using? 

$ `docker image ls` 

What version does the tag say? The current version is 5.1.2.

**Comment by iknowjason** [comment]
image tag is latest:

```
ubuntu@ip-10-130-10-5:~$ docker image ls
REPOSITORY            TAG       IMAGE ID       CREATED        SIZE
postgres              latest    5861c038d674   7 days ago     371MB
grafana/grafana       latest    a38f70e6466e   10 days ago    213MB
dustinupdyke/ghosts   latest    3765e1c383e6   6 months ago   117MB
ubuntu@ip-10-130-10-5:~$
```

**Comment by iknowjason** [comment]
This is the docker-compose.yml that we are using:
https://github.com/cmu-sei/GHOSTS/blob/master/src/Ghosts.Api/docker-compose.yml

Which should be pulling the api container.  Is this correct or should there be a different one?

**Comment by sei-dupdyke** [comment]
Not sure it makes a difference, but would you please try updating line 36 to:

`image: dustinupdyke/ghosts:5.1.2`

then

```
docker compose down
rm -rf db_data
docker compose up -d
```

**Comment by iknowjason** [comment]
Thanks.  I just tried all of those steps above.  Still no ClientTimeline data showing via querying the endpoint with curl or using grafana.  It does show a new version of the container with a different image ID:

```
ubuntu@ip-10-130-10-5:~$ docker image ls
REPOSITORY            TAG       IMAGE ID       CREATED        SIZE
dustinupdyke/ghosts   5.1.2     ab64561a3dad   43 hours ago   119MB
postgres              latest    5861c038d674   7 days ago     371MB
grafana/grafana       latest    a38f70e6466e   10 days ago    213MB
dustinupdyke/ghosts   latest    3765e1c383e6   6 months ago   117MB
ubuntu@ip-10-130-10-5:~$
```

**Comment by sei-dupdyke** [comment]
Sheesh, sorry for all this, it's supposed to be an easy `docker compose up -d` and you're done.

Do a `docker logs ghosts-api` and see if it tells us something?

**Comment by iknowjason** [comment]
Are the ghosts clients hard-coded in the source code to use a specific POST URL for the ClientTime?  Or is there a configuration parameter somewhere for this?  When I looked in the application.json, I see about four different PostUrl variables in the json that control where the client sends its data to the different endpoints.  So just curious about how it works under the hood for timeline data.

**Comment by iknowjason** [comment]
Output from docker logs:

```
ubuntu@ip-10-130-10-5:~$ docker logs ghosts-api
             ('-. .-.               .-')    .-') _     .-')
            ( OO )  /              ( OO ). (  OO) )   ( OO ).
  ,----.    ,--. ,--. .-'),-----. (_)---\_)/     '._ (_)---\_)
 '  .-./-') |  | |  |( OO'  .-.  '/    _ | |'--...__)/    _ |
 |  |_( O- )|   .|  |/   |  | |  |\  :` `. '--.  .--'\  :` `.
 |  | .--, \|       |\_) |  |\|  | '..`''.)   |  |    '..`''.)
(|  | '. (_/|  .-.  |  \ |  | |  |.-._)   \   |  |   .-._)   \
 |  '--'  | |  | |  |   `'  '-'  '\       /   |  |   \       /
  `------'  `--' `--'     `-----'  `-----'    `--'    `-----'
GHOSTS API 5.0.0.0 coming online...
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {993c313d-e0e1-4e28-aa14-9408ac72e4dd} may be persisted to storage in unencrypted form.
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:5000
Application started. Press Ctrl+C to shut down.
Application is shutting down...
             ('-. .-.               .-')    .-') _     .-')
            ( OO )  /              ( OO ). (  OO) )   ( OO ).
  ,----.    ,--. ,--. .-'),-----. (_)---\_)/     '._ (_)---\_)
 '  .-./-') |  | |  |( OO'  .-.  '/    _ | |'--...__)/    _ |
 |  |_( O- )|   .|  |/   |  | |  |\  :` `. '--.  .--'\  :` `.
 |  | .--, \|       |\_) |  |\|  | '..`''.)   |  |    '..`''.)
(|  | '. (_/|  .-.  |  \ |  | |  |.-._)   \   |  |   .-._)   \
 |  '--'  | |  | |  |   `'  '-'  '\       /   |  |   \       /
  `------'  `--' `--'     `-----'  `-----'    `--'    `-----'
GHOSTS API 5.0.0.0 coming online...
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:5000
Application started. Press Ctrl+C to shut down.
ubuntu@ip-10-130-10-5:~$
```

**Comment by sei-dupdyke** [comment]
No, not hardcoded, but pulled from here

```json
"ClientResults": {
    "IsEnabled": true,
    "IsSecure": false,
    "PostUrl": "http://ghosts-c2:52388/api/clientresults",
    "CycleSleep": 9000
  },
```

... this is the config for the client to post timeline updates. If a client doesn't post up its results, then you'll see comms errors in the client app.log file.

Try this on docker host:

```bash
docker exec -it ghosts-api /bin/bash
psql -U ghosts
select * from history_timeline order by id desc limit 10;
```

are there results in there?

**Comment by sei-dupdyke** [comment]
The hope is that on initial setup, you just have to change this portion of the URLs in application.json:

http://`ghosts-c2:52388`/api/clientresults

The part /api/clientresults should _not_ be changed.

**Comment by iknowjason** [comment]
Excellent feedback, this is what I was looking for on the PostUrl for clienttimeline.  This is what we have.  The ```{ghosts_ip}``` renders the actual IP address:

```
  "ClientResults": {
    "IsEnabled": true,
    "IsSecure": false,
    "PostUrl": "http://${ghosts_ip}:5000/api/clientresults",
    "CycleSleep": 9000
  },
```

I'm checking out the rest of these.  Thanks!

**Comment by iknowjason** [comment]
Just switched to the ghosts-postgres container.  Take a look, now showing some data!

```
ubuntu@ip-10-130-10-5:~$ docker exec -it ghosts-postgres /bin/bash
root@b46cad361c93:/# psql -U ghosts
psql (13.4 (Debian 13.4-1.pgdg110+1))
Type "help" for help.

ghosts=# select * from history_timeline order by id desc limit 10;
 id |              machineid               |     createdutc      |    handler     |         command         |
               commandarg                                                                                  | result | tags
----+--------------------------------------+---------------------+----------------+-------------------------+------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------+--------+------
 91 | fc94b025-6647-442e-ba73-e15a38fb3960 | 2021-10-01 14:59:58 | Command        | exit                    |
                                                                                                           |        |
 90 | fc94b025-6647-442e-ba73-e15a38fb3960 | 2021-10-01 14:59:57 | Command        | explorer \\dc01\sales   |
                                                                                                           |        |
 89 | 2d6692d4-bda1-41c7-b3be-8556c79c0175 | 2021-10-01 14:59:21 | Command        | exit                    |
                                                                                                           |        |
 88 | 2d6692d4-bda1-41c7-b3be-8556c79c0175 | 2021-10-01 14:59:20 | Command        | explorer \\dc01\finance |
                                                                                                           |        |
 87 | fc94b025-6647-442e-ba73-e15a38fb3960 | 2021-10-01 14:59:11 | Word           | create                  | %homedrive%%homepath%\Documents
 ```

**Comment by sei-dupdyke** [comment]
Awesome! 

API port doesn't matter, 5000 or whatever is fine. As long as clients are configured to use that same port.

Is data showing in Grafana?

**Comment by iknowjason** [comment]
No data is showing in Grafana under the "TIMELINE BREAKDOWN" window.

![Screen Shot 2021-10-01 at 10 37 49 AM](https://user-images.githubusercontent.com/4335973/135648332-d253f514-3491-457c-940f-ac52308e6542.png)
 "

**Comment by sei-dupdyke** [comment]
Click on the red/pink tab in the left corner of that widget, it may not have associated the datasource correctly. It should be "GHOSTS".

**Comment by iknowjason** [comment]
Interesting.  This is what I get when I click on the red/pink tab.

![Screen Shot 2021-10-01 at 12 19 03 PM](https://user-images.githubusercontent.com/4335973/135661389-e511c05a-2dd7-4345-bc70-ceed22b9d8e5.png)

**Comment by sei-dupdyke** [comment]
I think it is on the data tab there where you change your data source to "GHOSTS". 

On another screen it looks like this:

![image](https://user-images.githubusercontent.com/43444464/135663486-de091dfe-85a2-4f00-8d0c-75c77b39d508.png)

**Comment by iknowjason** [comment]
I have not been able to find where the data source setting is just for that UI widget.  It is using data source of "GHOSTS" because all of the other data is showing within the Grafana dashboard.  The error message is this:  

```
failed to convert long to wide series when converting from dataframe: long series must be sorted ascending by time to be converted
```

Which Grafana dashboard are you using?  I'm using the one with the name:  ```GHOSTS-5-default-Grafana-dashboard.json```

**Comment by sei-dupdyke** [comment]
I'm using that one as well. Try this instead, in the center where it says "TIMELINE BREAKDOWN" and choose "Edit":

![image](https://user-images.githubusercontent.com/43444464/135666967-fe3073da-e48a-42f9-8be8-6255d5ab96ae.png)

Then you will see the screen where I took my screenshot from. Is that dropdown set to "GHOSTS"?

**Comment by iknowjason** [comment]
yes it is.  Sorry, I wasn't clicking on the "edit".  I see it now.  This is what it looks like.


![Screen Shot 2021-10-01 at 1 10 19 PM](https://user-images.githubusercontent.com/4335973/135667510-364d0eb7-a211-430f-9f24-d11a9e422d39.png)

**Comment by iknowjason** [comment]
What version of grafana are you running?  I am running:   Grafana v8.1.5 (c725a4259a)

Based on the error message I showed you others have had the same issue after upgrading grafana, found this description of the problem:  

https://community.grafana.com/t/grafana-8-0-incompatibilities/48840

Here is the error message:  
```
failed to convert long to wide series when converting from dataframe: long series must be sorted ascending by time to be converted
```

**Comment by sei-dupdyke** [comment]
🤯  - I had an old grafana container, version 8 seems to have a bug.[1](https://community.grafana.com/t/grafana-8-failed-to-convert-long-to-wide-series-when-converting-from-dataframe-long-series-must-be-sorted-ascending-by-time-to-be-converted/53240)[2](https://stackoverflow.com/questions/69085007/grafana-8-1-1-postgresql-exception-long-series-must-be-sorted-ascending-by)

Change the query from ending in DESC to ASC. It appears grafana still displays it correctly.

```sql
SELECT
  handler as "Handler",
  count(*) as "Executions",
  date_trunc('minute', createdutc) as "time"
FROM
  history_timeline
group by handler, date_trunc('minute', createdutc) 
order by date_trunc('minute', createdutc) ASC
```

**Comment by sei-dupdyke** [comment]
I pushed an updated grafana dashboard file too, sorry about that.

**Comment by iknowjason** [comment]
Yep, I saw it was a bug too probably right when you did.

**Comment by iknowjason** [comment]
I'm going to rebuild my range with the new dashboard.

**Comment by iknowjason** [comment]
I think that fixed the bug issue.  Thanks!  One last question.  This is what my TIMELINE data looks like now.  Is this normal that the lines are blank.  I do see off to the right that it is capturing some of the application runs, but I don't see anything visual in the middle.  Good sign that it no longer says "No data." for sure.


![Screen Shot 2021-10-01 at 2 21 14 PM](https://user-images.githubusercontent.com/4335973/135675519-be24f8e8-f089-453c-a87f-d0dadc1bf71c.png)

**Comment by iknowjason** [comment]
What does yours look like for example?  I don't have a frame of reference for what it should look like with normal data.  But it's a very good sign that the errors and "No data" is now gone!

**Comment by sei-dupdyke** [comment]
Zoom in on the traffic that you see in the topmost chart, sometimes you don't see much until you get way in (or have a lot of clients reporting in).

**Comment by iknowjason** [comment]
I see a little bit more data now when drilling in.

Thanks for all of your excellent help.  I think we can close this!
