### ISSUE TITLE
Trouble finding the api

### ISSUE THREAD

**Issue by araminty** [cmu-sei/GHOSTS#87]
I'm seeing a similar thing to https://github.com/cmu-sei/GHOSTS/issues/85
When I try to access the api at `localhost:5000/api/home` it fails.  However I can access the api at `http://172.19.0.3:5000/api/home`, obtained with the command `docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ghosts-api`
And when I look at docker logs ghost-grafana, I see a large number of errors like this:
```
logger=context traceID=00000000000000000000000000000000 t=2022-06-09T16:02:36.31+0000 lvl=eror msg="Failed to look up user based on cookie" error="user token not found"  
logger=context traceID=00000000000000000000000000000000 userId=0 orgId=0 uname= t=2022-06-09T16:02:36.31+0000 lvl=info msg="Request Completed" method=GET path=/api/live/ws status=401 remote_addr=172.19.0.1 time_ms=0 duration=542.266µs size=27 referer= traceID=00000000000000000000000000000000
```
It seems like it's looking for the api at 172.19.0.1 and not at 172.19.0.3 where I can access it.  None of the dashboards are populating.  I can hit both the postgres and grafana on localhost.  I'm running on ubuntu 20.04.

**Comment by sei-dupdyke** [comment]
Hi, what does `docker ps --all` output?

**Comment by araminty** [comment]
I was able to connect by manually updating the grafana data connector.  Also the connection error logs seem to have not be reproduced when I recreated the containers.  The api not being accessible on localhost is still occurring but I dont think I see any other behavior being affected.

Docker ps shows:
```CONTAINER ID   IMAGE                 COMMAND                  CREATED         STATUS                   PORTS                                         NAMES
7d91524be5a5   dustinupdyke/ghosts   "dotnet ghosts.api.d…"   2 minutes ago   Up 2 minutes             0.0.0.0:52388->5000/tcp, :::52388->5000/tcp   ghosts-api
6fca0eea5519   grafana/grafana       "/run.sh"                2 minutes ago   Up 2 minutes             0.0.0.0:3000->3000/tcp, :::3000->3000/tcp     ghosts-grafana
bf6b46d33f78   postgres              "docker-entrypoint.s…"   2 minutes ago   Up 2 minutes (healthy)   0.0.0.0:5432->5432/tcp, :::5432->5432/tcp     ghosts-postgres
```

**Comment by sei-dupdyke** [comment]
Check out this SO article on specifying the IP that the containers bind to within the compose file:

https://stackoverflow.com/questions/45109398/how-can-i-make-docker-compose-bind-the-containers-only-on-defined-network-instea

HTH
